### PR TITLE
Add notice that the WIN32-INSTALL Instructions are deprecated

### PR DESCRIPTION
**Pull request by x2764tech**
I've wasted a bit of time trying to follow these old instructions, and, from the look of the issues log and developers forum, I think other people have too.
I've tried to update the Wiki with information as I find it, and this change just adds an instruction to future developers to look elsewhere.

### CODE REVIEW

**Comment by liversedge** [comment]
Thanks for this David, its really appreciated.

I will wait for Joern to review and merge since he's much more experienced with the Windows builds. I must confess I have neglected the developer guides and instructions.

Mark

**Comment by Joern-R** [comment]
@x2764tech Thanks for adding and sorry for wasted effort - I will merge and since the demand for building under Windows to contribute is increasing - I will start working on an updated guide over the next days. You find first info on how to build on the appveyor.yml - but I will work on giving a "from scratch" guide.

**Comment by Joern-R** [comment]
@x2764tech I never considered it a complaint - for long time no-one was asking - and I actually went through 3 different ways to build on Windows (starting using mingw, msys2,...). With our move to MSVC2015 and a a last step to QT 5.8 things are now much easier for the mainline. So your feedback is fully appreciated to get this now finally documented

**Comment by liversedge** [comment]
Everyone is so polite :)

Anyway.. if you are building, you must have something you wanted to develop?

What did you have in mind? (And how can we help)

CHEERS

**Comment by x2764tech** [comment]
I'm hoping to implement #337 (see #2348 ) - the task itself doesn't seem _that_ hard, but getting a development environment setup is proving to be the stumbling point at the moment.

**Comment by liversedge** [comment]
Perfect, there is also this post on the forums that I will followup, since we could include a database of coefficients to choose from at the same time (https://groups.google.com/d/msg/golden-cheetah-users/vqeqdOxkUck/VHcW_NbvAgAJ).

We could just publish it as a csv or something on goldencheetah.org/trainers.csv ?

**Comment by x2764tech** [comment]
Is this how the system currently works for other reference data (screen layouts, etc)?
But yes, the ability for people to fork the website repo and edit the CSV list would be great.

The only concern I do have about a CSV is having some kind of reference once someone's chosen the co-efficients, and in case they are tweaked later on... and if people might expect this to back-propogate into their training history... but that's probably a problem for a different day.

Some things I've noticed from the code:

- Some trainers curves are based on MPH rather than KPH. My math isn't good enough to do the conversion, so I might include this as an option.
- `BT-ATS - BT Advanced Training System` is based on RPM rather than velocity (so may have to stay hard coded for the moment)
- Different trainers have different _`n`_ for  `Σ  `**_`a`_**<sub>_`n`_</sub>**_`x`_**<sup>_`n`_</sup> - I was think **_`a`_** would be a `std::vector<double>` (or Qt equivalent), and require the csv to have zeros for if it doesn't apply (like the current `Kurt Kinetic` trainers)

So, I'd imagine the csv to look like this (I've typed this by hand, so excuse any mess)

```
name,mph,n,a[n]...
Kurt Kinetic - RoadMachine,1,4,0,5.244820,0,0.019168
1UP USA,1,4,25,2.65,-0.42,0.058
MINOURA V100 on 4,0,4,-10,3.4036,0.1825,-0.00173
```

It might make it easier to have a fixed size of _`n`_, but some of the issues refer to _`n`_` >= 8`, so it would be a lot of zeros for most trainers...

**Pull request merged**
