### PR TITLE
Optimize splines and bikesim dvdt.

### PR DESCRIPTION
**Pull request by ericchristoffersen**
Optimize cubic interpolator coefficient processing. Lazy coefficient processing is 4-10x faster. This has no effect on values.

Update bicycle sim dvdt calculation to return direct slope instead of interpolated slope. 2x faster and more accurate.

### CODE REVIEW

**Comment by ericchristoffersen** [comment]
Issue is here:

#3350

**Comment by ericchristoffersen** [comment]
Travis failed because of some quadtree damage. Needs restart.

**Comment by ericchristoffersen** [comment]
Pull is still pending so added more stuffs. Was smoothing a gpx with 480k entries. Found profound issues with file that size, mostly about detecting and dialing back the gradient descent if it runs of the rails.

This change also dials back distance length compute to no longer measure to the nanometer.

**Comment by liversedge** [comment]
I don't feel confident in assessing this code, but since its isolated I'm happy to merge.
Are you happy with it at this point?

**Comment by ericchristoffersen** [comment]
Yes. Good to merge. I'm happy with it.

________________________________

**Pull request merged**
