### PR TITLE
Support for TTS files.

### PR DESCRIPTION
**Pull request by ericchristoffersen**
Add ability to read tts files into ergfile format for trainer mode. I've tested only with the few old tacx tts files I own.

Training mode now can record altitude even if lat/lon are not present (some older tts files.) This is done by deriving altitude from slope and distance.

Fix numerical stability issues in cubic and quadratic solvers caused when one coefficient dominates the others.

I was surprised to see the altitude data in my tts files is very noisy which leads to noisy slope. It is slightly distracting but for me it isn't a huge deal. An option we have is to ignore the altitude data in the tts and instead derive it from the tts' slope. Downside of this is that the altitude won't sum to the correct altitude for the ride, but their canned slopes are very smooth.

### CODE REVIEW

**Comment by ericchristoffersen** [comment]
Second commit takes care of the problem with bad altitude data. ErgFiles from tts have their altitude data declared "untrustworthy". This means that train mode will just use the sample slopes instead of computing it from altitude. Restructured the altitude, slope and location grovelling to handle all the different cases.

Another fix: dont let sim bicycle roll backwards. Negative v goes to zero.

At this point the behavior is pretty good with my TTS files. Needs bake time.

**Comment by ericchristoffersen** [comment]
#347

**Comment by ericchristoffersen** [comment]
With last commit I've given up on the tts altitude info. It is simply too noisy. Now the tts loading always recomputes altitude based upon the gradient recorded in the tts file. Thus the altitude in the loaded file wont match reality but it will match the tts gradient, and metrics like VAM will be valid when riding tts files.

**Comment by Ramoonus** [comment]
if you need help to test, i`ve got some TTS4 movies to verify on my W10 PC

**Comment by ericchristoffersen** [comment]
> if you need help to test, i`ve got some TTS4 movies to verify on my W10 PC

Thanks Ramoonus. That would be great. I'm keen to hear what issues are present, especially how gc experience compares to the authentic tacx experience.

The ttsfile is loaded to an internal erg file which is then used for the training ride.

The ergfile from tts will always have altitude. This is a number that is faked using the gradient info present in the tts. If there is no location data then the altitude will always start at zero. For rides without locaiton data I'm keen to know if tacx has stored the stashed a starting altitude somewhere...

For tts with location data I am still deriving altitude from gradient. I do this because the altitude in the tts files I've seen is really terrible and doesn't match the tacx gradient. I figure it is better to show the actual vertical meters that you rode on your trainer instead of some fantasy number from the tts file.

The ergfile playback in gc always derives gradient from a continuous curve through the derived altitudes. This means gc will display a continuously changing gradient. Is that also how tacx works? Do you like it?

I have made no changes in how golden cheetah synchronizes distance to video. I would love to know if you think there is a bug here. Several sorts of bad synchronization I'd like to hear about:

sync always off by a constant offset
sync gets worse as ride goes on
sync varies through ride

**Comment by ericchristoffersen** [comment]
Just found a really wicked error. The ttsreader was computing altitude from ride distance and gradient. But tangent vector during ride was computed from location on path spline constructed from location. The tangent vector gets stretched and squished when there is a big difference between ride distance and geo location... Fix is to compute altitude change using location distance delta, not ride distance delta.

**Comment by ericchristoffersen** [comment]
Lot of good stuff here. Only issue I can see is a slight slope instability (+/- 0.2) on some switchbacks on the stelvio.

There are still the open questions of if there's a way to synchonize altitude on no altitude files and if the starting distances are correct. The mountain passes look pretty well synchronized to me.

**Comment by ericchristoffersen** [comment]
Ok. Slope is now perfect. I had neglected to account for when parametric speed was different than the average. Tried a bunch of rides and they all seem to behave well.

I think this change is ready to go.

**Comment by liversedge** [comment]
Perfect. Can you add a short description to the commit, nothing fancy just a brief description, a couple of lines will do. Then will merge.
PS: Make lines no longer than 50 characters in length.

**Comment by ericchristoffersen** [comment]
Description: will do... I noticed something after doing a ride yesterday and have another small change that looks good.

Here is the current state, when loading erg file I spherical interpolate the duplicate points. Pretty much a linear interpolation.

slerp

I changed the duplicate interpolation to use cubic splines instead:

cubicInterp

In no way does this effect ride effort (doesnt change gradient or distance) but looks lots better I think. Given how noisy and inaccurate the gps data can be I literally have no trustworthy points so I'm tempted to do a bspline averaging instead, but that'll be another change.

So anyway, I will play with this new hotness a bit and re-push when ready. Will add a description at that point.

**Comment by liversedge** [comment]
Why is altitude encoding in json changed?

I'm not sure that is relevant to TTS support -- we are super sensitive to changing the file format and encoding -- it generally requires a lot of testing. Was it in the patch previously? I don't recall seeing it.

**Comment by ericchristoffersen** [comment]
I did just change altitude precision with this latest commit. This is the same issue I had before with lat/lon. The altitude store in json hasn't enough resolution. Currently only 2 digits. It makes the slope very rough and ugly on steep switchbacks when I'm riding slope. Slope is now beautiful with high resolution. Is this actually considered a file format change?

**Comment by ericchristoffersen** [comment]
Here is same switchback on stelvio with the current 2 digits:

altitude_two_digits

And here is with change:

altitude_more_digits

**Comment by ericchristoffersen** [comment]
My memory paged in. The issue is that the default fp write precision for the stream is only 2. The altitude is currently being written as float but only 2 digits. After the json change its being written as float with unbounded precision - exactly the same as lat/lon.

**Comment by liversedge** [comment]
The fact you didn't need to change the parser on reading suggests this is ok. I just feel a little uncomfortable with it in this commit. But lets be pragmatic about it. I'm not gonna make you do a separate patch :)

Think its ok, seems churlish otherwise.

**Comment by Sigfreid74** [comment]
@ericchristoffersen  - Great work on this project - I am very interested in being able to make the most of my old tts files and videos. Did you end up getting RLVstudio and RLVworkbench? I have copies if you still needed them.

**Comment by ericchristoffersen** [comment]
> @ericchristoffersen - Great work on this project - I am very interested in being able to make the most of my old tts files and videos. Did you end up getting RLVstudio and RLVworkbench? I have copies if you still needed them.

Thanks for feedback. I'd love to hear how this tts support compares with what tacx app does. My tts files are working well for me but haven't heard anything critical (and I like criticism.)

I have pretty much given up on trying to produce rlv (and tts), I wrote something that can make an rlv but the editing experience is just really poor, and the math is indeterminate. I think the rlv format being speed/based is really unfortunate and hacky. They are closed formats and producing them is quite involved. The old rlv/pgmf system sucked because there were two files that had to be kept in sync, the newer tacx tts format is much better because there is only one stream of data: distance is the single axis which provides slope, location and video time, but tts is quite involved to write, I think lots of unnecessary fiddly bits.

So instead of requiring tts golden cheetah now supports playing saved json activities directly. To make a videosync ride you do the outdoor ride recording video and gps data. You can edit the ride as an activity using the spreadsheet style edit window. Because you recorded gps and video at the same time their time is synced. Edit the ends of the ride so the start/end times match up (easy if you always start video before gps record, end gps record before stopping video). If you have video sections you want to remove (like a rest stop), then edit them out in video editor, making careful note of start/end time of section you removed, now in golden cheetah edit window remove the samples that correspond to that time segment. Voila the time and distance and location remain synced. I've tried this for a few play rides, just to prove it, but I don't have a reasonable system for recording (I mostly mountain bike.)

**Comment by Sigfreid74** [comment]
Hi Eric,
Thanks for getting back to me. I currently trying to get my old "non-smart" Tacx Genius trainer (T2020) to work with a different project (FortiusANT) so I can then connect up to Golden Cheetah and the like. (that team have successfully been able to hook up a "non-smart" Tacx Vortex. ) I am also wondering if you have a program that converts the TTS to RLV/PGMF or even GPX? Is your GC TTS file reader able to output the file to JSON or  GPX?
Overall I am hoping to future proof the day when TTS4 or the computer it is on fails me....

Thanks

**Comment by Sigfreid74** [comment]
Hi Eric - The FortiusAnt group has finally cracked the Genius signals - and Golden Cheetah can now recognise the non-smart Genius as an FE+C trainer. I can now run my old tts videos on GC - It works thanks to your code! Do you know of a way to create segments of videos within the GC system - ie just the climbs for example?

**Comment by ericchristoffersen** [comment]
That is great news!! Such a waste to have these old trainers gathering dust.

I'm so happy you are using the tts support. The tts unpacking was all thanks to the WattZap project on github, most of my work was just porting it from java to c++.

Segments of video: that sounds like something you should suggest on the golden cheetah user group.

**Comment by Sigfreid74** [comment]
Yes it will make a lot of use of some pretty good hardware out there. A lot
of people are of course interested in Zwift - but I love the RLV's. The tts
files have courses (usually the climbs built into them. No way to access
them in GC? I'll ask the user group.
Thanks Eric.

**Comment by ericchristoffersen** [comment]
Look what an informed user can achieve! Having never used the tacx software I had no idea there were 'courses' defined within the tts file. That sounds like another 'issue' you should bring up in the user group. Sounds neat.

There are a few tokens in the tts that we currently ignore. "Segments". It could be they are the info you want.

Can you please tell me a bit about courses? What does it achieve? Also please point me at a tts file that has 'segments'? And tell me where those segments lie on the course? Then I can figure out how to get that same data from the tts.

**Comment by Sigfreid74** [comment]
OK, Thanks Eric, I'll get that to you in a day or so. In a longer video such as the "Route de Grand Alps" which may contain 3 or 4 climbs, the courses are usually the individual climbs. As far as I can tell there is no way to make smaller segments inside GC when loading a .tts file.

**Comment by ericchristoffersen** [comment]
I don't really understand what the purpose of the 'sections' or 'courses' is, but if you think its neat explain why and maybe someone will add it. I'd like to understand the appeal.

Right now every press of the fwd and back buttons in train mode teleports you by 1km. If there's a section I like (the middle switchbacks on the stelvio) then I will just click back 5-6km to repeat that part. Similarly I often skip long descents by clicking ahead.

**Comment by Sigfreid74** [comment]
Hi Eric,
Here is a collection of screenshots from tts4 with the courses / segments shown. As you can see on a long video like this one it is very handy if you want to quickly setup a ride for just one of the climbs (usually enough for me in one session). [https://drive.google.com/drive/folders/1Zsaf1wepWio0_GUjBqhb2JU9PxFXQjVu?usp=sharing](url)

**Comment by ericchristoffersen** [comment]
Excellent. I had no idea. I never bothered to implement the string decoding. I just tried it out and indeed there are segments with the names. Its just like you said.

I'm not sure whatall we'll do to make these things accessible from train mode, there's nothing in the ergfile datastructure, nor in the ui that would let you choose the segments, but I might as well enable the full decode from the tts reader.

Here's an example:

[ segment name ]
[ "Route 1/8 - Gorges du Cians" ]
149490  [ 0x7ff7dd2d6640 149490 0x7ff7dd2d5770 ]:  0 . 1041  v 1000   10 x 1 
block type  1041  version  1000 
[segment range]  0 - 21.7388 / 1

For now I will scoop these all into a segment list in the tts reader.

**Comment by ericchristoffersen** [comment]
Ok, I have submitted a change to do the parsing and bubble route title and description to the ergfile. At last the route name is now visible while riding. The segments and segment descriptions are parsed now but there's nowhere to put them. Baby steps!

#3668

**Comment by Sigfreid74** [comment]
Brilliant Eric! Can I do anything to help / test changes?
Matthew

**Comment by ericchristoffersen** [comment]
> Brilliant Eric! Can I do anything to help / test changes? Matthew

Unfortunately the empirical different with this change is to just see the route title while training. Not so exciting. But rest assured the datastructure inside now sees all the segments, etc. There's still quite a bit of work to be done to make it actionable. How exactly should we change the ui so that these segments can be used? The problem is that, as far as I know, its just tacx' tts that have these segments, so we can't turn the world upside down just for that.

It was super useful for me to see the screenshots. I've never seen the tts software.

Probably the most useful thing you could do is to document the stuff you want to see and explain it on the user group. Sell it. Then someone might step up and make the ui changes that are needed.

**Comment by Sigfreid74** [comment]
Hi Eric, I will try and put a proposal forward. I do have another question though; when selecting train mode, what information is coming from the "workout" file vs the "videosync" file. Can you select different Workout files for any given videosync file?  Or do the titles have to match? Could a "workout" file be created to refer to certain segments of the videosync and avi files?
Matthew

**Comment by ericchristoffersen** [comment]
File purposes: easiest explanation is what isn't in the workout file.
The movie is... the movie. It maps time to a picture.
The videosync file is a list of number pairs that are used to map distance to time.

With videosync file and a movie you can map distance to a picture. Yes?

The workout is everything that isn't the movie and the videosync file.

Workout files must contain distance and then either wattage or slope. That is the minumum. Sometimes workout files include time and they can be used as videosync files (because you can map distance to time with them.)

You are free to select any combination of workout, movie and videosync. If the distance or times don't match then the workout will end when you run off the end of one.

Custom Videosync to ride a piece of a ride. Sure, you could do that. Simply map distances to different times. You can map distance to movietime however you like as long as distance and time are both monotonic. We don't support reverse movie playback :).

But if you had a perfect workout slopes and videosync for a movie, I wouldn't touch it. Much easier to just ride the distance range that you want to ride (like how segments are described in the tts.) Would be simple to just say: "I want to ride from 100 to 150km", than to muck about making new videosync, there is just no point.

Perhaps the easiest thing to do for segments:
-fix how location is chosen, it isn't reasonable to click fwd 150 times to go ahead 150km. Maybe we could increase the step size as clicks are made quickly.
-it'd be nice to see the segment descriptions, maybe on the videoscreen, as you cross their boundaries.
- maybe have a tile that shows the description too...

I'm closing my eyes and imagining and I don't really imagine having segments available to choose would make my virtual rides better. I think I'd rather just click to where I want to ride and then ride it, instead of picking something first and needing to stick to it.

Perhaps there should be some sort of meta ride that drives the selection of workout, video,videosync, and it could be set with any sequence, including segments within a ride, and also to chain together other rides.

But I'm not really sold on it for what I do. Wrong place to discuss. Bring this to the user group!

**Comment by Sigfreid74** [comment]
OK Eric, I have taken the plunge and tried to describe my "ideal" GC training setup on the google user group. Thanks for the detailed info, I understand a bit better now. Another thought: One other thing a segment could do would be to display distance to the top of a climb as a training incentive?

**Comment by ericchristoffersen** [comment]
Distance to top of next climb... that is a cool idea! Maybe we could base climb upon the uci definition of climb and show the ranking. Sort of an auto-segment feature. Love it. I think you should open a new issue with this suggestion.

Hey the change to put the ride segments into the training mode is partly done now. You'll see lap boundaries at the segment boundaries. But the names are really hard or impossible to read and there's no way to select them by name. Try it out and then open issues about the things you think are broken.

**Comment by THannoverS** [comment]
I've just installed 3.6-dev , but am unable to locate this exciting tts-import feature  .  
Currently i've looked after it 
- in activity/import from file .. but this do no list .tts as supported formats, and the impoter chokes if I select my .tts   from the wildcard *.* option.  (my tts file  is straight out of TTS4).
- in tools/ import workout , but that one 'chokes' on the tts-files as well

What am I missing out here ?

**Pull request merged**
