### PR TITLE
LTMWindow: Fix missing include when building NOWEBKIT without GC_HAS_…

### PR DESCRIPTION
**Pull request by erikboto**
…CLOUD_DB

### CODE REVIEW

**Comment by liversedge** [comment]
What platform are you trying this on?

I've found that Linux is not /too/ bad, but OSX is terrible.
Be interested to hear your feedback.

**Comment by liversedge** [comment]
Also, that fix would be better placed in LTMWindow.h

**Comment by erikboto** [comment]
It's on Windows, figured I might as well give it a try since you mentioned you were curious on the status on Windows. Anything in particular I should test?

**Comment by liversedge** [comment]
Basically RideSummaryWindow uses QWebEngine and on OSX it flashes and renders badly and when in tiled mode the rendering goes berserk. Of particular note is moving the mouse in and out of a summary window causes it to go blank and vanish then return!

Linux seems ok though, so curious if Windows has the same problem

**Comment by erikboto** [comment]
Hmm, I missed that there was a #ifdef for NOWEBKIT in the header. But isn't it generally better to keep the includes in cpp unless they are actually needed in the header, less including should keep build time down. But that might be optimizing too much?

**Comment by liversedge** [comment]
Fair point.

**Comment by erikboto** [comment]
I've been playing around with the ride summary in both tiled and tabbed mode for a couple of minutes, and I don't see anything weird (yet).

**Comment by liversedge** [comment]
Oh that is good news.

Damien is looking at the getting Bing/Google maps and Ride view working too.

**Pull request merged**
