### PR TITLE
Overview - Multisport awareness for Sparkline & Up/Down

### PR DESCRIPTION
**Pull request by amtriathlon**
Two small features to try on Overview:
1) Add metric description as ToolTip to METRIC Card
2) Consider only activities with matching sport tags to compute Sparline and Up/Down indicators

### CODE REVIEW

**Comment by liversedge** [comment]
Must confess, I'm not a fan of tooltips... on a related topic I'm thinking about classifying all the metrics, so they can be browsed rather than selected from a list... any thoughts on a taxonomy?????

**Comment by amtriathlon** [comment]
TBF they don't look pretty on Ubuntu, but I think description is something useful to show on METRIC Cards, may be using other way...
WRT to taxonomy some categories may be:
Volume
Intensity
Distribution (aka Time in Zones)
Stress
Measures

**Comment by amtriathlon** [comment]
Removed the tooltips commit, now it only restrict the activities considered to compute Sparkline and Up/Down markers to those matching sport flags since comparisson across sports is usually meaningless.

**Comment by liversedge** [comment]
I like your taxonomy -- its sufficiently broad and consistent -- THANKS!

**Pull request merged**
