### PR TITLE
Added swim XData for SML lap swimming files

### PR DESCRIPTION
**Pull request by amtriathlon**
One record per length with the same conventions
used for FIT files.

### CODE REVIEW

**Comment by mondoshiwan** [comment]
Hi Alejandro,
cool…!
may i ask for another feature request. One of the main advantages of Ambits is that you can write your own apps and record them to the sml file. Would be nice if these 'app data' could be imported to the xData too. E.G. for swimming i build a simple Rest Time Counter to determine the intervals, with that additionel data it could be helpful to fix the interval lenght in future.
Or for my rides i have created an own real time slope calculator…

Ambit can run 5 apps at a time max, but you don't have to store all of them. Format can be integer, float or time. Right behind the header in a sml file the apps are defined.

`<Apps>
			<App>
				<Name>SWIC-2-1</Name>
				<AppId>10414323</AppId>
				<Format>Integer</Format>
				<Prefix>int</Prefix>
				<Logged>True</Logged>
				<Displayed>True</Displayed>
				<Running>True</Running>
			</App>
			<App>
				<Name>TotalRestTimeV_</Name>
				<AppId>10411403</AppId>
				<Format>Time</Format>
				<Prefix>Rest</Prefix>
				<Logged>True</Logged>
				<Displayed>True</Displayed>
				<Running>True</Running>
			</App>
			<App>
				<Name>sendoff</Name>
				<AppId>10547230</AppId>
				<Format>Time</Format>
				<Logged>False</Logged>
				<Displayed>True</Displayed>
				<Running>True</Running>
			</App>
`

In the data section they stored then like this:

`<AppsData>
					<AppData>
						<AppNumber>2</AppNumber>
						<Value>94</Value>
					</AppData>
					<AppData>
						<AppNumber>1</AppNumber>
						<Value>3</Value>
					</AppData>
				</AppsData>
`

testfile:

[C8C70A511B001500-2016-11-25T07_05_32-0.sml.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/613272/C8C70A511B001500-2016-11-25T07_05_32-0.sml.zip)

this would be an awesome killerfeature… there is no other way to pull that data out of Movescount, till now…

what do you think?

thx in advance, carsten

**Comment by amtriathlon** [comment]
Hi Carsten, this is a Pull Reques, can you file this in a new Feature Request?
Thanks!
BTW: length by length records in Edit->SWIM tab can be easily fixed (you can edit, add or remove lengths), then you need to run Edit->Fix Lap Swim from Length Data tool which will update pace and distance.

**Comment by mondoshiwan** [comment]
Sorry, i will pull a request!

note: i don't have that swim tab… yet. in v4 with sml files


Am 25.11.2016 um 14:40 schrieb Alejandro Martinez:

**Comment by amtriathlon** [comment]
2016-11-25 10:44 GMT-03:00 mondoshiwan <notifications@github.com>:

> note: i don't have that swim tab… yet. in v4 with sml files
>
Right, this is what this pull request adds! It will be available in v3.4.1

**Pull request merged**
