### PR TITLE
Code Cleanup - Remove Query State from ErgFile

### PR DESCRIPTION
**Pull request by ericchristoffersen**
Move ergfile query state from ergfile to callers.
Factor out the code that establishes the query bracket.
Make ergfile query methods const.

### CODE REVIEW

**Comment by liversedge** [comment]
simulated rider class is not required for this?
should it really be included in this pull request?

**Comment by ericchristoffersen** [comment]
SimulatedRider not used. A future step is to integrate it into trainsidebar, remove a bunch of cruft. Should really help to clean it up. Another guy is using the simulated rider to build training 'rabbits' and he was rebased off this branch.

**Comment by ericchristoffersen** [comment]
I redid the recent fix for MRC/ERG files. Rather than test current execution state I changed trainsidebar to test the ergfile format. Added hasGradient() and hasWatts() so we dont need to test format itself. Logic is that altitude and gradient do no harm when running in ERGO mode, currently its impossible to run in ERGO mode without an MRC or ERG format file, but in future we might switch to ERGO mode in the midst of a simulated ride (forcing intervals while climbing the stelvio.) The real error in previous code was using the watts data in the mrc file as gradient data (they share same field in point.)

This change also comments out SimulatedRider in bicyclesim.

Main point of this change is still to pull the location state out of the ergfile so that the ergfile becomes data instead of an active participant in real time data state. This is mainly done so multiple locations can be queried without hosing the query state.

**Comment by ericchristoffersen** [comment]
Latest (and probably last) commit:

Removes the 'km' and 'manualOffset' fields from the VideoSync object. Instead routeDistance is tracked using the 'routeDistance' field on the trainsidebar. This is a very nice simplification since now VideoSync object is purely stateless data.

While testing this change I found two related issues:
- route distance tile prints as km int, not floating point in user units
- distance tiles were rounding to nearest, not truncating to meter

This pull request now fixes these issues:

https://github.com/GoldenCheetah/GoldenCheetah/issues/3416
https://github.com/GoldenCheetah/GoldenCheetah/issues/3498
https://github.com/GoldenCheetah/GoldenCheetah/issues/3499

Both VideoSync and ErgFile are now stateless.

**Comment by ericchristoffersen** [comment]
This change seems good and ready.

**Comment by ericchristoffersen** [comment]
Resolved conflicts on rebase.

**Comment by human705** [comment]
Hi Mark,

Is it possible to merge these changes? I have a prototype of a simulated rider pacing the user and attacking at random intervals to enhance the training experience for the user. But it is based on Eric's changes.

Thanks 

Peter

**Comment by ericchristoffersen** [comment]
Ok, this is re-re-re-rebased so works again against latest sources. Can someone please review? Is healthy to get the duplicate state out of the shared ergfile and videosyncfile objects.

**Comment by ericchristoffersen** [comment]
More cleanup and reorg. Iterator now maintained by adapter that implements all the query methods. Kept ErgFile* as const as possible. I think this is a pretty nice separation. I sure would like everyone to stop using global access to get to current ErgFile... While testing these changes I found and fixed #3580 , so that fix is here too.

**Comment by ericchristoffersen** [comment]
When using intensity adjust on slope training file, intensity was allowed to reach zero, which zeros the slope and which is not recoverable. Fix is to prevent slope intensity adjustment from going below 1%. Elevation widget now draws new elevation graph when route elevation is adjusted. Change is detected by comparing saved ymin/ymax against ergfile ymin/ymax. While doing this discovered existing elevation widget code was iterating over entire file to recompute ymin/ymax. Ergfile didn't previously hold or compute ymin so added that field. Now make use of ergfile's ymin/ymax instead of iterating. Also use 0 and Duration instead of iterating to compute xmin and xmax...

**Comment by ericchristoffersen** [comment]
#3582

**Comment by ericchristoffersen** [comment]
Can someone (Mark?) please take a look at this?

**Comment by ericchristoffersen** [comment]
Hi, I now have several trees that are relying on this and the rebasing is getting complicated. Is there a problem with this change or approach it takes? Please let me know what is wrong and I can fix it.

**Comment by ericchristoffersen** [comment]
This also fixes #3589

**Comment by ericchristoffersen** [comment]
@liversedge Hi Mark. Is it possible to get some feedback on this? Thanks!

**Comment by ericchristoffersen** [comment]
Fix more merge conflicts.

**Comment by ericchristoffersen** [comment]
FfwdLap works great, even rapid fire. Also a RewindLap method to ErgFile, ready for its button.

**Comment by amtriathlon** [comment]
I reviewed and tested and the stateless ErgFile looks like a better solution, it is merged by https://github.com/GoldenCheetah/GoldenCheetah/commit/25bb4beaa50b0d2068ed333fd8494c312f3ac711 to include the core part (fixes #3416) and a fixed RewindLap implementation.
All other pieces were separately merged and simulated rider class better be introduced when (and if) it is effectively used.
Thanks for your hard work and let's see how it works in the wild.

**Pull request closed without merging**
