### PR TITLE
LibUsb::OpenFortius - Remove call to usb_set_altinterface() 

### PR DESCRIPTION
**Pull request by mattipee**
Was known bad on OSX, proved an issue on LINUX (for me), and to be tested on WINDOWS following its removal.

I believe creating this PR will produce an artefact that is testable.

### CODE REVIEW

**Comment by mattipee** [comment]
@mickyduck55 you're running on Windows, correct? I've merged master so it has all the Fortius changes.

Please could you test this branch once compiled if you have time? I'll also test it (I have Win7Pro available).

Otherwise, I can revert and disabling only on MacOS+Linux. leaving the behaviour for Windows untouched.

**Comment by Mickyduck55** [comment]
@mattipee <tunabiscuits796@gmail.com>
yes I am on Windows 10 do I have to wait for @Ale Martinez
<amtriathlon@gmail.com> to publish a snapshot build or can I download this
like I could the Artifact builds I have been testing (and still using) from
the first pass at this?
Cheers

**Comment by Mickyduck55** [comment]
@mattipee yes I am on windows 10... I can give this a brief test later.. I have done my ride today ....... Anything in particular you would like me to test, is there anything different I should notice ?
ATM I am still using the Artifact from @ericchristoffersen that he put together when the PRs were split off. ....

**Comment by mattipee** [comment]
It should either work or not, but give it a calibrate, a few connect/disconnects, start/stops, pedal a minute or so. That's pretty much what I'll do.

**Comment by Mickyduck55** [comment]
OK @mattipee <tunabiscuits796@gmail.com> have downloaded it probably leave
it until tomorrow thanks for implementing

**Comment by Mickyduck55** [comment]
Hi @mattipee
all worked as expected  connected reconnected calibrated from cold, during
ride after ride no problems.... 60 seconds seems a long time just sitting
... so  much so I timed it.. 60 seconds it is LOL
Re rolling cal... Would be good but I think more complete option that would
solve other issues would be have the buttons available at "Pause"
Today messing with this testing all my figures are really poor because
after exiting I decided I didnt want to ride the first 30 mins again so
while getting to the re start position my cadence, speed, HR etc are all
wrong as they are counting from when I press "play"..
I will post something on the forum...
Cheers

**Pull request merged**
