### PR TITLE
Function to create an intervall between two existing intervals

### PR DESCRIPTION
**Pull request by ragman1976**
Take the end of the first interval as start of the new intervall between and the beginning of a following intervall as end.

### CODE REVIEW

**Comment by liversedge** [comment]
Can you rebase this PR please ?

I can't commit like that

Ta
Mark

**Comment by ragman1976** [comment]
Hey Mark,

I don`t realy know what to do? To which branch should I rebase?

Greets

**Comment by liversedge** [comment]
your pull request contains a large number of merge commits, you need to rebase your repo and resubmit.
look at the pr on github if you can't see the issue.

**Comment by amtriathlon** [comment]
> Take the end of the first interval as start of the new intervall between and the beginning of a following intervall as end.

I can't find any commit from the OP, Is this a proper Pull Request implementing this feature or just a misplaced Feature Request?

**Comment by liversedge** [comment]
Closing it as it seems spurious.

**Pull request closed without merging**
