### PR TITLE
Add libusb-compat v0.1.5

### PR DESCRIPTION
**Pull request by antoniusriha**
This is a workaround for the Linux USB freeze issue as discussed in
PRs #2149 and #1641. This PR doesn't include any code changes,
instead it adds and statically links libusb-compat. libusb-compat
exposes the same API as libusb-0.1 (0.1.12) but uses libusb-1.0 as
a backend. This library has been downloaded from
https://github.com/libusb/libusb-compat-0.1/releases/tag/v0.1.5.
The location of libusb-1.0 can be controlled via LIBUSB_INSTALL
in gcconfig.pri.

Maybe this could be merged for the 3.4 release. I don't consider
this a long-term solution or replacement of PR #2149.

### CODE REVIEW

**Comment by liversedge** [comment]
Similarly -- I'm happy to merge if this is deemed solid on Linux.

**Comment by gcoco** [comment]
Hi. If we want a GC specific libusb-compat then lets make it its own repository, I don't see the point of installing another library's source code when we make no changes to it. Linux/Mac already point out installing libusb-1.0 and libusb-compat already. Personally move with the build with libusb-1.0 out of the box if we only want libusb-1.0.

**Comment by liversedge** [comment]
I'll take your advice Gareth -- should this PR be closed?

**Comment by gcoco** [comment]
Closing as documentation advises using libusb-compat and prefer to deploy libusb-1.0 code.

**Pull request closed without merging**
