### PR TITLE
Makefile that captures details on how to build GC on raspberry pis

### PR DESCRIPTION
**Pull request by drio**
Captures in a Makefile all the commands necessary to build GC on a raspberry pi.

Based on [this great](https://github.com/GoldenCheetah/GoldenCheetah/wiki/Building-Golden-Cheetah-on-a-Raspberry-Pi-4-on-a-fresh-Raspbian-Buster-install) wiki entry.

Also, I'd like to point out that booting the PI via USB reduces the build time from 1:30 hours to 30 min. I can add a comment to the wiki document if you find it useful.

I have not been able to run GC yet with my trainer since GC does not find my ANT+ devices (including my trainer). I can expand on the document as I continue working on this. 

-drd

### CODE REVIEW

**Comment by amtriathlon** [comment]
Experience shows GC config.pri edition is the more error prone step, specially since steps in the wiki are not exactly described and require some common sense, perhaps you can consider adding that steps or may be just the finished config.pri since that build is frozen to v3.5

**Comment by drio** [comment]
> perhaps you can consider adding that steps or may be just the finished config.pri since that build is frozen to v3.5

I think that is what I am doing. I have the final, edited `config.pri` and this [target](https://github.com/GoldenCheetah/GoldenCheetah/pull/3695/files#diff-9ef33b1a0d8ddf416ba0e2ff285e3bf072da726da31012a7ba9d2e8d7a41b46cR33) copies that version into the src directory prior to start the building process. 

Let me know if that is what you wanted or there is something else you want me to do.

**Comment by amtriathlon** [comment]
> > perhaps you can consider adding that steps or may be just the finished config.pri since that build is frozen to v3.5
> 
> I think that is what I am doing. I have the final, edited `config.pri` and this [target](https://github.com/GoldenCheetah/GoldenCheetah/pull/3695/files#diff-9ef33b1a0d8ddf416ba0e2ff285e3bf072da726da31012a7ba9d2e8d7a41b46cR33) copies that version into the src directory prior to start the building process.

But that file is not included in your PR so that step will fail for a regular user, or am I missing something?

**Comment by drio** [comment]
You are right. I thought the .pri file was in the PR. It wasn't. 
It is now. See latest [commit](https://github.com/GoldenCheetah/GoldenCheetah/pull/3695/commits/6d3c993fa08a8e188ecfd1a573133c1bfd2a9b84).

Thank you.

**Comment by amtriathlon** [comment]
Great! Can you add some usage instructions to readme document?

I mean prerequisites, how to start the build and which results to expect, assuming this is intended for non-technical users.

An alternative is to add this to the wiki, but I think would be better if it is self contained and linked to the wiki once it is merged.

**Comment by drio** [comment]
I expanded the README to explain how to run the Makefile. I also added some comments in the Makefile itself. 

I think I am going to run it myself one more time to make sure everything still works fine after the changes.

I'd like to eventually be able to build off of master and maybe even generate a binary version for RPI.

**Comment by drio** [comment]
I followed the instructions in the readme and everything builded fine.
Unless there is something else, this is ready to merge.

**Comment by amtriathlon** [comment]
Thanks David, I will merge this in current master since it makes simpler for users to find and v3.5 is frozen.
Once merged it will be a good idea to reference in the wiki entry.
WRT building current master, it has 2 additional dependencies WebEngine and GSL, if you can find or build them, there should be no problems, but better to switch the discussion to the forums.

**Comment by drio** [comment]
> it has 2 additional dependencies WebEngine and GSL

When you say webengine you mean the qtwebengine?

**Comment by amtriathlon** [comment]
Yes, see https://github.com/GoldenCheetah/GoldenCheetah/blob/master/INSTALL-LINUX

**Pull request merged**
