### PR TITLE
Add debugging options to select the log file, format and rules, and redirect stderr

### PR DESCRIPTION
**Pull request by michelrdagenais**
This NEEDS to be tested on Windows BEFORE merge! 

Recently, when trying to debug an issue, it was very difficult to get proper debugging logs on windows. The redirection of stderr to goldencheetah.log on Windows did not work. When you do not redirect the output to a file, and have a lot of debugging log entries sent to the console, this changes the timing. Moreover, capturing the output log from the console often resulted in only getting the last thousand lines or so. In addition, more information was needed in log entries, like the timestamp, to better understand the timing. 

This PR hopefully solves the stderr redirection problem on Windows. I have read about the issue, and possible solutions, and believe that the PR should work. However, I could not test it. From what @amtriathlon mentioned, the behavior on Windows 10 and Windows 8 is different and both should be tested. Perhaps @mattipee has access to older Windows releases. In addition, this PR has an option to specify the log file (not having to search where goldencheetah.log is hidden, or keeping more than one log file), specify the logging rules (what logging to activate or not) and the logging format. I tried to provide an interesting default logging format. Do not hesitate to propose something better.

### CODE REVIEW

**Comment by michelrdagenais** [comment]
The ci failure on Mac seems related to a python version issue, and totally unrelated to this PR.

**Comment by amtriathlon** [comment]
> The ci failure on Mac seems related to a python version issue, and totally unrelated to this PR.

No, the failure is due to the hard 50’ build time limit on Travis, we are near the limit with macOS builds and sometimes they fails, I can restart the build if you want, but I am afraid there is a bigger issue with this PR and it is it will not work on Windows, IME.

**Comment by michelrdagenais** [comment]
It was painful but I now have fairly clean code that works on Linux (POSIX) and Windows 10. I have a friend who should soon try it on Windows 7. It does redirect write(2, ...), fprintf(stderr, ...), qDebug(), std::cerr, and on Win32 WriteFile(GetStdHandle(STD_ERROR_HANDLE), to the log file.

Hopefully, the redirection will also work on Windows for new threads like the one created for the Fortius. @Mickyduck55 could you test it with the Fortius on Windows? The extensive logging in Fortius.cpp is not in this branch, but at least the Fortius version number is printed on stderr and should appear in the log file.

GoldenCheetah --debug
    The Fortius version should be printed on the console

GoldenCheetah
    The Fortius version should in file C:/Users/.../AppData/Local/GoldenCheetah/goldencheetah.log

GoldenCheetah --debug-file test.log
    The Fortius version should be in file test.log in the current directory

If you want to have tons of messages, you can activate the Qt debug messages by adding option --debug-rules

GoldenCheetah --debug-file test.log --debug-rules "*.debug=true"

**Comment by Mickyduck55** [comment]
Thank you Michael.. I don't want any messages, I  just want it to work ;)
Windows 7 is 12 years old?
BUT without you and @mattipee <tunabiscuits796@gmail.com>  this would be
dead..

**Comment by michelrdagenais** [comment]
It works on Windows 7 as well for all the levels mentioned (write(2, ...), fprintf(stderr, ...), qDebug(), std::cerr, and on Win32 WriteFile(GetStdHandle(STD_ERROR_HANDLE)). Let see if @Mickyduck55 can get some Fortius messages, from another thread, in the log file as well.

**Comment by Mickyduck55** [comment]
Downloaded artefact so will give it a go.. thanks

**Comment by Mickyduck55** [comment]
@michelrdagenais 

just tested as requested no time to ride today but the second syntax does show that output to a specific file, using --debug-file works, if debugfile is used log is goldencheetah.log

The syntax
START "" "C:\program files\golden cheetah\goldencheetah.exe" --debugfile C:\DEBUG\test1.txt writes the file to the GC log 

The Syntax
START "" "C:\program files\golden cheetah\goldencheetah.exe" --debug-file C:\DEBUG\test1.txt writes the file C:\DEBUG\TEST1.txt

**Comment by michelrdagenais** [comment]
@Mickyduck55  what is the content of TEST1.txt? Writing to the file was already tested on Windows 10 and 7. The objective here is to check that the output from the Fortius thread goes nicely in the log file. Could you share Test1.txt or at least check that it contains an entry with the Fortius motor brake version? Thanks!

> The Syntax
> START "" "C:\program files\golden cheetah\goldencheetah.exe" --debug-file C:\DEBUG\test1.txt writes the file C:\DEBUG\TEST1.txt

**Comment by Mickyduck55** [comment]
[12:06:48.244] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.244] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.244] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.244] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.244] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.245] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.245] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.245] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.245] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.245] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.246] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.246] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.246] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.246] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.246] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:51.312] debug: connecting.. (unknown:0)
[12:06:51.370] debug: "Motor Brake Unit Firmware=4100 Serial=5997\n
 year=2008 type=T1941\n    Version2=2327 MotorBrake=1" (unknown:0)


Hi Michael yes it does write the motor brake information

**Comment by Mickyduck55** [comment]
Updated file after selecting a route
[12:06:48.244] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.244] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.244] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.244] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.244] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.245] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.245] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.245] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.245] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.245] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.246] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.246] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.246] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.246] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.246] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:51.312] debug: connecting.. (unknown:0)
[12:06:51.370] debug: "Motor Brake Unit Firmware=4100 Serial=5997\n
 year=2008 type=T1941\n    Version2=2327 MotorBrake=1" (unknown:0)
[12:09:31.986] debug: LAPS: (unknown:0)
[12:09:31.986] debug: 0 :  1  start: 0 km, rangeId:  1 km, name:  "Part 1 -
Ronde Hoep" (unknown:0)
[12:09:31.986] debug: 1 :  2  start: 22.439 km, rangeId:  1 km, name:  ""
(unknown:0)
[12:09:31.986] debug: 2 :  3  start: 22.439 km, rangeId:  2 km, name:
 "Part 2 - Amsterdam City" (unknown:0)
[12:09:31.986] debug: 3 :  4  start: 34.963 km, rangeId:  2 km, name:  ""
(unknown:0)
[12:09:31.986] debug: TEXTS: (unknown:0)
[12:09:31.986] debug: 0 :  0  duration:  22439  text: "Part 1 - Ronde Hoep:
 [0m ->22439m]" (unknown:0)
[12:09:31.986] debug: 1 :  22.439  duration:  12524  text: "Part 2 -
Amsterdam City:  [22439m ->34963m]" (unknown:0)

**Comment by Mickyduck55** [comment]
Updated again at manual disconnect in train view
[12:06:48.244] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.244] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.244] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.244] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.244] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.245] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.245] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.245] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.245] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.245] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.246] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.246] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.246] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.246] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:48.246] warning: QWidget::paintEngine: Should no longer be called
(unknown:0)
[12:06:51.312] debug: connecting.. (unknown:0)
[12:06:51.370] debug: "Motor Brake Unit Firmware=4100 Serial=5997\n
 year=2008 type=T1941\n    Version2=2327 MotorBrake=1" (unknown:0)
[12:09:31.986] debug: LAPS: (unknown:0)
[12:09:31.986] debug: 0 :  1  start: 0 km, rangeId:  1 km, name:  "Part 1 -
Ronde Hoep" (unknown:0)
[12:09:31.986] debug: 1 :  2  start: 22.439 km, rangeId:  1 km, name:  ""
(unknown:0)
[12:09:31.986] debug: 2 :  3  start: 22.439 km, rangeId:  2 km, name:
 "Part 2 - Amsterdam City" (unknown:0)
[12:09:31.986] debug: 3 :  4  start: 34.963 km, rangeId:  2 km, name:  ""
(unknown:0)
[12:09:31.986] debug: TEXTS: (unknown:0)
[12:09:31.986] debug: 0 :  0  duration:  22439  text: "Part 1 - Ronde Hoep:
 [0m ->22439m]" (unknown:0)
[12:09:31.986] debug: 1 :  22.439  duration:  12524  text: "Part 2 -
Amsterdam City:  [22439m ->34963m]" (unknown:0)
[12:10:58.362] debug: disconnecting.. (unknown:0)
[12:10:58.408] debug: connecting.. (unknown:0)
[12:10:58.468] debug: "Motor Brake Unit Firmware=4100 Serial=5997\n
 year=2008 type=T1941\n    Version2=2327 MotorBrake=1" (unknown:0)
[12:11:02.130] debug: disconnecting.. (unknown:0)

**Comment by michelrdagenais** [comment]
Excellent, with this it will be much easier to get logging output from users. Moreover, when writing to a file, it will not affect much the timing, which may be an important factor when interacting with devices like the Fortius.

@amtriathlon there is an issue with the filename and line number. It is not available in release builds and outputs an unsightly (unknown:0). I will update the default format to have it only in debug builds. Anything else you would like me modify before updating the PR to be "ready to merge"?

**Comment by michelrdagenais** [comment]
It is READY TO MERGE. It was tested on Linux and Windows 10/7 and works well. It should help getting complete log messages, with timing information, efficiently written to a file instead of to the console.

**Comment by michelrdagenais** [comment]
@amtriathlon I am happy with the PR, it works well on Linux / Windows 10 / Windows 7 and IMO is ready to merge. Is there anything else that you want for that PR?

**Comment by amtriathlon** [comment]
Hi Michel, great you have found a solution for low level io redirection on Windows!
I will merge it and let's see what happen in the wild. Thanks!

**Pull request merged**
