### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by ihewitt**
Some more simple performance improvements that make the startup a bit snappier.
1. Helps startup time a bit more, mainly by removing all of the QTextEdit controls used for html esacping and moving them into a utils namespace.
2. Stopped excessive looping in setYMax where axis height was small.

### CODE REVIEW

**Comment by liversedge** [comment]
nice!

protect/unprotect are a dirty little secret. thanks for cleaning it.

**Comment by jonbev** [comment]
It's nice to see that it is actually loading with the progress but I kind of feels like we're back to where we used to be with the progress bar on the loading screen.

Is there any way the loading can be multi threaded to speed it up? On my laptop it only uses one core.

**Comment by liversedge** [comment]
the progress dialog is not part of this update. plus its loading the backing store from file and is only at startup and takes < 20 secs!

**Comment by jonbev** [comment]
I'm afraid it take 1:10 for me. Thats running on a I5 laptop with SSD. Processing power definitely seems to be the bottleneck for me.

**Comment by liversedge** [comment]
?

You are talking about little box that loads showing 1% - 100% as it goes?
How many rides do you have?

Mark

**Comment by jonbev** [comment]
Yes the 1 - 100%

1058 activities.

**Comment by liversedge** [comment]
If its a real concern I’d swich off interval discovery.

**Comment by jonbev** [comment]
Does that run every time you startup? Surely not??

**Comment by liversedge** [comment]
How much memory does your PC have available ?
You are using 64bit ?

**Comment by liversedge** [comment]
Its loading the backing store RideDB.json.
Should take seconds.

Suspect there are either a gazillion ijtervals found or your PC has a memory issue.
Do you use the formal builds or your own?

Send me your RideDB.json and I’ll see why it might have an issue.

**Comment by jonbev** [comment]
I have 8gig.

GC is running as 32bit. I built my own. I'll try the 64bit release you've just done.

**Comment by jonbev** [comment]
Just loaded in 23secs with the 64bit version. 

I have sent my rideDB to see what you think.

**Pull request merged**
