### PR TITLE
Ignore SetLoad in Null trainer

### PR DESCRIPTION
**Pull request by ericchristoffersen**
NullTrainer was honoring SetLoad which makes no sense and breaks testing. Null trainer should only generate load, not honor what is set.

### CODE REVIEW

**Comment by amtriathlon** [comment]
I think this is intended since it allows to use the Robot device to simulate ERG mode, manual or using a workout, which is useful for demos and general understanding. This change breaks that functionality without any benefit I can see.

**Comment by ericchristoffersen** [comment]
> I think this is intended since it allows to use the Robot device to simulate ERG mode, manual or using a workout, which is useful for demos and general understanding. This change breaks that functionality without any benefit I can see.

Null trainer is a strange cookie because it emulates both a device and rider.

The workout sets load to aspire to. The current null trainer behavior honors set load as a command to the rider. Current behavior doesn't let me model, graph and analyze the case where load doesn't match desired erg load.

**Comment by amtriathlon** [comment]
> Current behavior doesn't let me model, graph and analyze the case where load doesn't match desired erg load.

There is a random variation added, may be the amplitude can be made larger. Other than that may be you can change when you are debugging without removing a useful functionality.

**Comment by ericchristoffersen** [comment]
> > Current behavior doesn't let me model, graph and analyze the case where load doesn't match desired erg load.
> 
> There is a random variation added, perhaps the amplitude can be made larger (and initial load higher to be more useful in simulated slope mode). Other than that may be you can change when you are debugging without removing a useful functionality.

The change won't seem useful until trying to demo intensity adjustment.

**Comment by amtriathlon** [comment]
Sorry but I don’t understand how this can be useful in a our current setup and it turns unusable a basic feature s.t. to use the Robot device in manual erg mode, besides workouts.

**Pull request closed without merging**
