### PR TITLE
travis-ci: include newer automatic build environment

### PR DESCRIPTION
**Pull request by Ramoonus**

### CODE REVIEW

**Comment by Ramoonus** [comment]
don`t pull it yet,
there seems to be more wrong (nothing to do with my patch though)

**Comment by Ramoonus** [comment]
github travis builds keep giving errors for translation includes; 
RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_fr.qm'

**Comment by amtriathlon** [comment]
> github travis builds keep giving errors for translation includes;
> RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_fr.qm'

This is harmless, as documented in the INSTALL* documents.

I cherry-picked and merge the language detection commit, thanks for the contribution.

WRT the upgrade to xcode 11.3 implies to switch to Mohave and we are building on the oldest officially supported version, which are High Sierra and Xenial for now.

**Comment by Ramoonus** [comment]
build matrix is corrupted

**Comment by amtriathlon** [comment]
Thanks, It is mostly cosmetic, due to indentation, but I will fix it anyway.

**Comment by Ramoonus** [comment]
the include matrix is still not present

**Pull request closed without merging**
