### PR TITLE
Save rim and tire size settings

### PR DESCRIPTION
**Pull request by antoniusriha**
This PR adds rim and tire size to the athlete's settings values (in addition to wheel size). UI elements for those settings have already been present, but the values have not been persisted so far.

### CODE REVIEW

**Comment by liversedge** [comment]
Hi,

Thanks for the PR .. why are you adding these?
Usually we add settings because we need to use them .. how will these settings be used?

THANKS!

Mark

**Comment by antoniusriha** [comment]
There is no other use than to save user input for rim and tire size, so the
combo box values can be set when loading the settings dialog. Otherwise
users might think the program is not working properly, if the inputted
values disappear between program runs.

**Comment by liversedge** [comment]
Sorry, I don't understand. What is the purpose of adding these?

**Comment by antoniusriha** [comment]
They are just there to set the resp combo box values in the athlete's tab
in the options dialog. No other use, just a usability improvement.

**Comment by liversedge** [comment]
The problem here is they are redundant, so no reason to add them and the maintenance overhead associated with them. There are several places where config is queried; REST api, datafilters, R api and they will all need to be updated.

There must be a reason you wanted to add them there?

**Comment by antoniusriha** [comment]
From a business logic standpoint they're redundant, because only the wheel
size is needed for calculations. From a usability standpoint I believe them
to be valuable, because it feels odd, if you open a dialog and values
you've inputted earlier are missing. Although the use of these two fields
in the UI is solely to calculate the wheel size, they don't convey the look
& feel of a "calculator", but rather of setting fields.
Also, I didn't know about the other places that would need to be changed
(REST api, R api, ...).
All in all I think the usability gain needs to be weighed against the
increased maintenance effort necessary, to decide if this PR should go in.
Alternatively, one could rebuild that part of the UI to convey a more
calculator type look & feel, e.g. by adding a button "Calculate" and
putting the fields in a separate dialog. This dialog could be reused in
other parts, e.g. during training device setup.

**Pull request closed without merging**
