### PR TITLE
Updated French Translation

### PR DESCRIPTION
**Pull request by amtriathlon**
Contributed by Arnaud Leclere

### CODE REVIEW

**Comment by ArnaudSB** [comment]
Thanks Ale.

1.There are still untranslated menus or terms, but I can not find these elements to translate them (I'm thinking of the "Share/Partager" menu for example (Or the "Tools>Options>Athlete>Measurements") - I can not find the elements with a Qt search, to translate them).

2.Two problems identified recently: The translation of "Curated Only" and "Uncurated Only" is not at all satisfactory for use. (To filter the shared graphics).

I'm waiting for Damien Grauser to identify other problematic elements before pushing another file here.

**Comment by MaksVasilev** [comment]
Hi!

> 1.There are still untranslated menus or terms, but I can not find these elements to translate them (I'm thinking of the "Share/Partager" menu for example (Or the "Tools>Options>Athlete>Measurements") - I can not find the elements with a Qt search, to translate them).

May be you need update strings in file *.ts to current source code base?

In "src" path:
lupdate src.pro

 Updating 'Resources/translations/gc_fr.ts'...
    Found 5369 source text(s) (405 new and 4964 already existing)
    Kept 377 obsolete entries
    Number heuristic provided 8 translation(s)
    Same-text heuristic provided 82 translation(s)

p.s. lupdate - console Qt tools.

With best regards,
Maks

**Comment by ArnaudSB** [comment]
Hello,
Thank you for these proposals, I am not able to do this alone.

Before working on the translation I downloaded the latest ts file. And the terms I do not find in the ts are terms that are not really new, they are menus that must exist from many versions.

Here is the last ts file I transferred to Damien Grauser for testing and validation.
I have since this transfer some changes to make but I wait for the return of Damien.

Hoping to have understood your remarks and proposals MaksVasilev.
BRegards,

[gc_fr_ALE.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2679446/gc_fr_ALE.zip)

**Comment by amtriathlon** [comment]
> Before working on the translation I downloaded the latest ts file. And the terms I do not find in the ts are terms that are not really new, they are menus that must exist from many versions.

The problem is those files are not automatically updated to the new texts included in source code, the lupdate command does that, I added a section on Guidelines explaining it.

The attached file is your translation after running lupdate on current master, it includes the missing texts: 
[gc_fr.ts.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2680418/gc_fr.ts.zip)

**Comment by ArnaudSB** [comment]
OK cool,
Thanks MaksVasilev
Thanks amtriathlon, perfect.
I'm going back to work this weekend ;-)

**Comment by ArnaudSB** [comment]
Hello everyone,
And here is my final, and _validated version from my point of view_.
Merry Christmas.
[gc_fr.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2710643/gc_fr.zip)

**Pull request merged**
