### PR TITLE
Added new metric "running-speed" to import of BSX csv-files. Fixed bugs in calculation of min(SmO2) and min(tHb)

### PR DESCRIPTION
**Pull request by gernot-hochmuth**
src/FileIO/CsvRideFile.cpp: 
Added import of new metric *running speed* from BSX-Insight CSV-file. Running speed is
converted from m/s to km/h or corresponding imperial units. Up to now it's not handled
if running speed data is given in imperial units in the BSX-Insight CSV-file.

src/Metrics/BasicRideMetrics.cpp:
Fixed calculation of `min(SmO2)` and `min(tHb)` which were faultily calculated as
`max(SmO2)` resp. `max(tHb)` before (possibly a copy and paste error). For `min(SmO2)` a simple logic is implemented to prevent leading zeros to be erroneously taken as `min(SmO2),` as we usually don't start our workout in an exhausted state beyond anaerobic threshold. Later on, after one non-zero value has been recorded, `min(SmO2)` might become zero. `min(tHb)` is supposed to be always larger than zero.

Please review.

### CODE REVIEW

**Comment by gernot-hochmuth** [comment]
Hello,
reviewing the compiler log of the failing Travis Cl build (job #958.1) I noticed several compiler errors due to type mismatch in R/RGraphicsDevice.cpp (Rboolean vs. bool). 
e.g.:
> R/RGraphicsDevice.cpp:91:12: error: cannot initialize return object of type 'Rboolean' with an rvalue of type 'bool'

> R/RGraphicsDevice.cpp:319:5: error: assigning to 'Rboolean' from incompatible type 'bool'

etc. These compiler errors are completely unrelated to this commit. Please re-check using a proper setup. Thank you.

**Comment by liversedge** [comment]
Those compiler errors were resolved a week ago.

**Comment by gernot-hochmuth** [comment]
is there more specific information what's failing with the AppVeyor build? For some strange reason the error message is truncated in a way that it's not meaningful any more. *unable to build non-...* does not help that much. Please re-check. Thank you!

**Comment by liversedge** [comment]
The build needs to be retried, its related to a previous commit.

**Comment by gernot-hochmuth** [comment]
OK, thank you for the clarification.
Regards
Gernot

Am 26. Juli 2016 09:36:55 MESZ, schrieb Mark Liversedge <notifications@github.com>:
>The build needs to be retried, its related to a previous commit. 
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/GoldenCheetah/GoldenCheetah/pull/1938#issuecomment-235186116

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by gernot-hochmuth** [comment]
meanwhile I fixed additional bugs in the calculation of *Avg(tHb)* and *Avg(SmO2)*. Beforehand  values of zero had been included in the calculation of the mean. but zero is not a valid value for *tHb* and *SmO2* (*tHb = 0 mg/dl* resp. *SmO2 = 0%*  makes  physiologically no sense for living human beings).

Sorry for bothering you. As I am new to GIT, I accidentally included these changes into my former pull request concerning the calculation of *min(tHb)* and *min(SmO2)* by uploading my changed source-file instead of opening a new pull-request.

**Comment by liversedge** [comment]
I think you need to create a new PR

**Pull request closed without merging**
