### PR TITLE
Provide zoneslow and zonescolor in GC.athlete.zones().

### PR DESCRIPTION
**Pull request by sisao**
Hi,
this commit provides the lower ends of the powerzones and the matching zone colors for R charts.

for Example:
activity <- GC.activity()
metrics <- GC.metrics()
date <- metrics$date

zone <- GC.athlete.zones(date=date, sport="bike")
lows <- zone$zoneslow
colors <- zone$zonescolor

p <- activity$power
p2 <- p[seq(1, length(p), 4)]
breaks <- c(unlist(lows), Inf)
cols <- c(unlist(colors))[findInterval(p2, vec=breaks)]

barplot(p2, space=0, border=NA, col=cols)

Is it possible to add this to GC or should this be done in a different way?

### CODE REVIEW

**Comment by liversedge** [comment]
nice.

**Comment by liversedge** [comment]
Can you update the wiki page to reflect the new changes?
https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Working-with-R

**Comment by liversedge** [comment]
Thanks for updating the wiki, nice job.

**Comment by sisao** [comment]
thx,
I will provide a better "power in zones" graph later today with screenshot, 
but I have to read a little more in the R documentation...

**Pull request merged**
