### PR TITLE
Use Qt Json Parser for Withings API (Fixes Issue #2764)

### PR DESCRIPTION
**Pull request by arunh**
Fixes issue #2764

### CODE REVIEW

**Comment by liversedge** [comment]
Brilliant -- thats great -- but did you update src.pro to reflect the source code name change?

**Comment by liversedge** [comment]
And now it also needs to be dependant on Qt5 .. we informally support Qt 4.8 for older platforms.

**Comment by arunh** [comment]
Hi Mark, I didn't see any references in src.pro relevant to the rename but apologies if I have missed something - it did seem to build/work fine on my workstation after a 'make clean'.

It's a good point about the Qt4 support, I didn't think of that. Your call on that one obviously - whatever you decide it was an interesting Friday afternoon activity!

**Comment by liversedge** [comment]
Ok will merge and fixup for Qt4.

**Pull request merged**
