### PR TITLE
Move to qwt 6 2 multiaxes

### PR DESCRIPTION
**Pull request by andreasbuhr**
Upgrading qwt 6.2 seems to be the hardest part.

The released qwt 6.2 seems to be lacking a so called "multiaxes" feature which is required for GoldenCheetah.
Here I placed the current "qwt-multiaxes" of qwt into the qwt folder and then fixed all compiler errors.

Open issues:

1. There are linker errors. The methods the linker is asking for do exist, so somehow there is a problem in the build system.
2. QwtSpline is now abstract. It interface changed considerably. Currently, usage of QwtSpline is commented out. This has to be fixed.
3. The enableAxis method is gone. Qwt source code suggests it is now synonymous to setAxisVisible. This needs testing.

### CODE REVIEW

**Comment by amtriathlon** [comment]
I am closing this since it was superseded by https://github.com/GoldenCheetah/GoldenCheetah/pull/4427

**Comment by andreasbuhr** [comment]
Cool

**Comment by amtriathlon** [comment]
BTW, thank you very much for your work, it took some time but I think now we can apply your PRs now to be able to build both with Qt5 and Qt6.

**Comment by thejockl** [comment]
Also a big thanks from my side for your awesome work! I even have a local version with your your PRs applied (plus some additional changes on later code), resulting in a mostly stable version linked against Qt6.

**Pull request closed without merging**
