### PR TITLE
Remove usage of QGLWidget

### PR DESCRIPTION
**Pull request by andreasbuhr**
QGLWidget was deprecated and is removed in Qt 6.

### CODE REVIEW

**Comment by amtriathlon** [comment]
TODO: adapt this to preserve current code behavior inside
```
#if QT_VERSION < 0x060000
#endif
```

**Comment by liversedge** [comment]
> TODO: adapt this to preserve current code inside
> 
> ```
> #if QT_VERSION < 0x060000
> #endif
> ```
> 
> besides to resolve the conflicts.

Let me test on Linux and Qt5 to see if it makes any real difference ?

**Comment by andreasbuhr** [comment]
Sure

**Comment by amtriathlon** [comment]
I resolved the conflict, the installer build failed due to the removal of Qt5OpenGL.dll, if we choose this route I will change the installer script, but perhaps it is better to keep without changes for Qt5 and remove QGLWidget for Qt6 only.

**Comment by liversedge** [comment]
It certainly makes a difference on Linux/Qt5- performance gets sluggish quickly on the user charts and overview

**Comment by andreasbuhr** [comment]
> It certainly makes a difference on Linux/Qt5- performance gets sluggish quickly on the user charts and overview

Can you clarify please, is this a big or a small problem?

**Comment by liversedge** [comment]
Ale has covered this in the commit, so keep it for builds < Qt6
Its not a huge issue, it will be interesting to see how Qt charts perform on Qt6 given they are still dependant on OpenGL

**Pull request closed without merging**
