### PR TITLE
Python data processors

### PR DESCRIPTION
**Pull request by riccioclista**
This PR adds the ability to create and execute python scripts that manipulate activity data, much in the same way as native data processors do. This enables the user to create their own data processors more easily. This PR adds the following features:
 * UI for managing python fix scripts (list, open for edit and delete)
 * UI for creating or editing scripts. This contains a PythonConsole (the same as in PythonChart) and the RideEditor-View. Scripts can be executed via this UI or by selecting them in the via the Menu "Edit" > "Python fixes".
 * a folder '.pyfixes' in GCROOT that contains all scripts. Scripts can be imported by simply dropping them into this folder
 * Python-API: Extension of the PythonDataSeries data structure to allow for setting values. Setting values is only enabled when run in the context of python data processor (not in PythonChart)
 * Python-API: New Method GC.deleteActivitySample(index, activity) to delete data rows
 * Python-API: New Method GC.deleteSeries(type,activty) to delete data columns
 * Command-Support for editing actions: All python script edits are wrapped in command contexts (LUW) to enable Undo and Redo
 * Integrate python scripts in existing data processor framework so they can be called on Save and Import
 * Python-API: New Method GC.postProcess(processor) to execute a data processor (python or non-python)
 * Python-API: new Method GC.createXDataSeries(xdata, series, unit)
 * Edit support of xdata series (via GC.xdataSeries(xdata, series))

### CODE REVIEW

**Comment by liversedge** [comment]
Looks really interesting.. be interesting to know when youre ready to merge.

**Comment by riccioclista** [comment]
Hopefully by next weekend. I'd like to add 2 more features: Integration with existing data processors framework, so they can be configured as import actions and the ability to call other data processors from python

**Comment by riccioclista** [comment]
- rebased on cur master
- implemented last 2 features mentioned above
- not yet extensively tested

**Comment by amtriathlon** [comment]
I think the Windows and OSX CI builds are failing since they don't include Python integration, since Python is optional the new code should be conditioned using #ifdef GC_WANT_PYTHON to avoid this problem.

**Comment by riccioclista** [comment]
- #ifdef GC_WANT_PYTHON and "Enable Python" setting are now being checked

**Comment by riccioclista** [comment]
I'll test it thoroughly this week so we can merge next weekend

**Comment by riccioclista** [comment]
I've fixed GC.postProcess python implementation, which requires special handling since it must invoke any child python data processors on the same thread, otherwise it will deadlock. I've tested all the new functionality in this PR and haven't found any issues so far. It can be merged.

**Comment by liversedge** [comment]
Do you have an example of using this?
Is it possible to have >1 script?

**Comment by riccioclista** [comment]
Number of scripts is not limited. Scripts are stored in a .pyfixes folder (goldencheetah/athlete/.pyfixes).

Here are 2 sample scripts:

- [convert_to_indoor.py.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/3083401/convert_to_indoor.py.txt) (removes lon/lat and alt series)

- [import_fix.py.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/3083402/import_fix.py.txt) (trims data at the start with HR or LON/LAT values of 0 and pads invalid altitude data)

Remove the .txt extension, put them into the .pyfixes folder and restart GC. Then you can see them under "Edit --> Python fixes".

**Comment by amtriathlon** [comment]
I started to play with this very nice feature and used one of the samples to fix a pending issue (https://github.com/GoldenCheetah/GoldenCheetah/issues/2113) and found a more interesting candidate would be  https://github.com/GoldenCheetah/GoldenCheetah/issues/2958, all is working as described, excellent!
I have not looked at the code yet, so I have a question:
I think we should restrict the use of the new Python APIs able to change data just to the Data Processor context and forbid its use in filter formulas an Python charts, is this included or have you see a way to include it s.t. them failing or having no effect on the unwanted contexts?

**Pull request merged**
