### PR TITLE
Add support for syncing to GoogleDrive.

### PR DESCRIPTION
**Pull request by gille**
This enables user to store GoldenCheetah files in their Drive accounts. The files are stored in the GoldenCheetah application data folder and are not visible to users. The directory name can be anything but must not conflict between athletes.

This uses GoogleDrive v2 API. The pull request also includes some fixes to OAuth handling for Google accounts in general.

### CODE REVIEW

**Comment by liversedge** [comment]
Awesome!

The build fails because there are no defaults for the SECRETS and KEYS.

These should be defined in Secrets.h (without the actual values) .. see the ones already in there.
We replace them (via sed) in Travis with gem secrets and users can define them in gcconfig.pri for local builds.

Really looking forward to playing with this :)

:+1:

**Comment by gille** [comment]
Ok. Just need to revert some of the JSON handling in the non QT5 code.

**Comment by gille** [comment]
And now it builds! Let me know if you want me to squash the commits.

I added directory support, even though directories in GoogleDrive don't behave like they do in your average file system.

**Comment by liversedge** [comment]
Excellent!

**Pull request merged**
