### PR TITLE
Fixes for user-visible messages and updated Russian translation, take two

### PR DESCRIPTION
**Pull request by prokoudine**

### CODE REVIEW

**Comment by liversedge** [comment]
Nice job !

Thank you for sticking with it, it really is much appreciated :)

**Comment by liversedge** [comment]
I will push a fix for the WPrime.cpp changes that do not compile.

**Comment by prokoudine** [comment]
Oh damn, I broke something? Sorry about that!

**Comment by liversedge** [comment]
Hey, your commit was huge. Thanks for all the effort !

**Pull request merged**
