### PR TITLE
Add XDG categories

### PR DESCRIPTION
**Pull request by probonopd**
This adds XDG categories that are needed so that the application shows up properly in the menu and can be added to https://appimage.github.io/.

Sports is not a standalone category as per https://standards.freedesktop.org/menu-spec/latest/apas02.html

Reference:
https://github.com/AppImage/appimage.github.io/pull/1193

### CODE REVIEW

**Comment by amtriathlon** [comment]
Thanks!

**Comment by probonopd** [comment]
Thank you. Please ping me once there is an AppImage with the fix available for download, then I can add it to AppImageHub.

**Comment by probonopd** [comment]
Thank you.

**Comment by probonopd** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/releases/download/v3.5-DEV1901/GoldenCheetah_v3.5_DEV1901_Linux_64bit.AppImage

still has 

```
[Desktop Entry]
Version=1.0
Type=Application
Name=GoldenCheetah
Comment=Cycling Power Analysis Software.
Exec=GoldenCheetah
Icon=gc
X-AppImage-Version=993eec8
```

No `Categories=`, I don't get it...

**Comment by probonopd** [comment]
Why is it in two places?

**Pull request merged**
