### PR TITLE
Update .gitignore to ignore the .prl file that is dynamically generated.

### PR DESCRIPTION
**Pull request by gille**

### CODE REVIEW

**Comment by liversedge** [comment]
The .prl file is also changed in this commit ?
Any chance you can submit with just the .gitignore changes?

**Comment by gille** [comment]
I could I suppose, the change as far as I see is because I deleted it from the repo.

**Comment by gille** [comment]
Ok, I've reverted libkqoauth.prl so now it just includes the .gitignore.

**Comment by liversedge** [comment]
Thanks!

**Pull request merged**
