### PR TITLE
FIxes for user-visible messages and updated Russian translation

### LINKED ISSUE #1410: Non-translatable messages in UI
src/WPrime.cpp, lines 71 through 74:

    { 0, 25, "W1", "Recovered" },
    { 25, 50, "W2", "Moderate Fatigue" },
    { 50, 75, "W3", "Heavy Fatigue" },
    { 75, 100, "W4", "Severe Fatigue" }

### PR DESCRIPTION
**Pull request by prokoudine**
This pull request fixes #1410 using solution suggested by Mark, changes a few occurrences of 'ride' to 'activity' (hopefully, correctly), fixes a typo in a user-visible message, and updates Russian translation accordingly (+ ca. 400 more translated messages).

### CODE REVIEW

**Comment by liversedge** [comment]
If you fixup the comment for 8fdcb735021d831cf1afc39d3840009746a2517c we can merge :)

**Comment by prokoudine** [comment]
(Duplicating another comment just in case.)

I think I'm a at loss here :)

I'm looking at src/xml/analysis-layout.xml and I see this:

So what is it exactly that I should do? 1) Revert my change and 2) add a line lile

titleMap.insert("Ride", tr("Activity"));

?

**Comment by prokoudine** [comment]
Well, crap. For some reason I thought it would be a jolly good idea to rebase before pushing changes to my repo, and now the pull request isn't clean (contains every other push from upstream repo since forking). Ideas?

**Comment by liversedge** [comment]
create a new pull request ?

**Comment by prokoudine** [comment]
Will do later today :)

**Pull request closed without merging**
