### PR TITLE
Resolve bugs in the WorkoutWizard (issue #1835)

### PR DESCRIPTION
**Pull request by tscode**
```
.. Corrected total distance for the metric summary in the Gradient
   Creator

.. Saving in .crs format now uses the right distance values (not
   cumulative distance)
```

### CODE REVIEW

**Comment by thomastaudt** [comment]
Browsing e.g. [http://www.racermate.net/coursesviewer.php](http://www.racermate.net/coursesviewer.php) for `.crs` files gave me this impression, yes. And if it really was

1 100
2 200
3 100

then the ErgFile importing had to be changed -- right now, it would 
create a 6km workout instead of a 3 km one.

**Comment by liversedge** [comment]
Sorry If I'm being awkward. Will check against the tests we already have for crs files tomorrow and merge. Have a good evening :+1:

**Comment by thomastaudt** [comment]
Absolutely no need to apologize. Glad if I could help :grinning:

**Comment by liversedge** [comment]
Apologies, this was missed in all other activity and is now stale so closing.

**Pull request closed without merging**
