### PR TITLE
Strava

### PR DESCRIPTION
**Pull request by gille**
Fix private file uploads - I made this a choice.
Let Strava upload .tcx.gz instead to save bandwidth

+ support for commute and trainer workouts on Strava.
+ move some files around for the keys.

### CODE REVIEW

**Comment by liversedge** [comment]
Is that commute/trainer metadata specific to strava or something specific to you?
It feels wrong! Should be metadata that the user maintains against the ride...

**Comment by liversedge** [comment]
Otherwise the compress/private stuff is great!

**Comment by gille** [comment]
It's specific to Strava AFAIK. Maybe others support this distinction as well but I agree, it should be moved to ride metadata.

**Comment by liversedge** [comment]
ah ok. lets go with it as it is.

thanks.

**Pull request merged**
