### PR TITLE
Adjust Video Playback speed on cyclist speed

### PR DESCRIPTION
**Pull request by vlcvboyer**
Hi,

This patch set adjusts Video Playback speed related to cyclist speed in training mode.
Needs RLV file to be used (a lot of AVI+RLV+PGMF sets are available for free: use google).
Valid when using libVLC 
see feature 382 linked to this amendment:
https://groups.google.com/forum/#!topic/golden-cheetah-developers/t9JFkSFLuv8

Note:
- This was pull request #1467 closed (by myself) due to mess in my git fork.
- Tested using Windows & libVLC + RLV + Tacx Vortex Smart
- It also includes ANT FEC commits from stschake as I includes it during my tests. This is not mandatory.
- I saw that a lot of cosmetic is also included as I likely remove trailing spaces before saving file wherever it is in the section I modified or not.
- a GPX selected from activities list can replace RLV (same way than street view). However I do not use it anymore. Thus I've not tested it with my latest fix...

Regards

Vianney

### CODE REVIEW

**Comment by liversedge** [comment]
Wow. You've been busy.

I will need to look at this closely - VLC is good for Win + Linux but need to think about how to make it work with QuickTime on Mac.

Will spend some time this weekend, but may take me a while to work through the whole thing.
I would rather separate FE-C into a separate commit, does it need to be folded in ?

THANK YOU

**Comment by vlcvboyer** [comment]
No FE-C can be discarded. It's just here because I used it for tests...
There is a dedicated commit for this merge (dbcc20f).
In any case the related files are clearly identified: "ANT*.*" !

This patch should not create any issues/bug with QuickTime on Mac... But it will definitely not synchronize video. If you have QuickTime documentation and a Mac for testing It should be easy to adapt it by yourself.

Regards

Note: Using it with speedometer overlay is perfect !

**Comment by liversedge** [comment]
Ah ok.

So all is VLC only, I can live with that :)

**Comment by vlcvboyer** [comment]
Only 4 lines are VLC! Most can be re-used for QuickTime.
At that time all are included within "#ifdef GC_VIDEO_VLC". This can be changed easily as it is located at the end only after computing target rate and time.

**Comment by vlcvboyer** [comment]
This is related to Feature Request #296

**Comment by liversedge** [comment]
I would still like to pursue this, if I pull all but the ANT file changes is that good enough ?

**Comment by vlcvboyer** [comment]
Yes: 3 of my branchs are independent:
video-sync = adjust video playback speed based on cyclist speed on trainer
trainview = meters overlays on video playback (speedometer, cadence, power...)
ant-fec = stschake contrib which I've extended with additional ANT messages such as slope simulation

I have ongoing modifications (add "none" in RLV file selection, visual aspect of meters...). But before I need feedback/comments in order to ensure that my contributions/features are in agreement with user expectations.

In any case this needs to be validated on other systems (mac+linux).

**Comment by vlcvboyer** [comment]
Hi,
Were you able to test this feature ?

At present there is a conflict with another modification on master branch. It's not really difficult to solve it but if you want me to withdraw those commits and create fresh ones resolving the conflicts I can do it. Is there any other good practice to synchronize my branch with current master ? It seems that "rebase" or equivalent functions are not to be used when pull request have already been submitted...
Let me know
regards

**Comment by liversedge** [comment]
If we could separate out ANT-FEC support and Video playback I will commit them separately.
The reason I want to do this is in case we need to revert either for a regression ?

I don't have a way of testing either but will test older functionality to make sure it still works...

THANK YOU :)

Mark

**Comment by vlcvboyer** [comment]
Except a mistake ANT-FEC is no more part of this pull request:
commit 2a44be3 has been released in order to revert commit dbcc20f (ANT FEC)
I've a separate branch for ANT-FEC ("ant-fec") which contincludes my additions.

**Comment by liversedge** [comment]
If you can point me to the pull-requests for ANT-FEC and Video playback I will merge them in ?

**Comment by vlcvboyer** [comment]
Hi,

Here are the several pull requests:

video playback:
https://github.com/GoldenCheetah/GoldenCheetah/pull/1522

ant-fec (both stschake and myself):
https://github.com/GoldenCheetah/GoldenCheetah/pull/1591

also this one fixes an issue with ANT speed or combo sensors speed calculation (not related to ANT-FEC but ANT protocol):
https://github.com/GoldenCheetah/GoldenCheetah/pull/1532

and this one correct an old comment in one ANT file:
https://github.com/GoldenCheetah/GoldenCheetah/pull/1541

**Comment by liversedge** [comment]
#1522 has conflicts, if you can make a clean pull request for this it would be great :)

**Comment by vlcvboyer** [comment]
How do you prefer ?
I delete my branch and related pull request then create a new one?
Or is there any other proper way to do it?

**Comment by liversedge** [comment]
I don't have any preference really, just need a clean pull request or patch and I'm happy to apply !

**Comment by vlcvboyer** [comment]
done!
video playback: pull request #1522 conflicts has been solved

FYI: You'll be able to test this feature with advanced home trainer or with a basic home trainer if you have speed sensor on your bike.
Free video files and associated sync files are available for download on several site such as cyclingrlv.com

**Comment by vlcvboyer** [comment]
done!
video playback: pull request #1522 conflicts has been solved

FYI: You'll be able to test this feature with advanced home trainer or with a basic home trainer if you have speed sensor on your bike.
Free video files and associated sync files are available for download on several site such as cyclingrlv.com

**Pull request merged**
