### PR TITLE
Don't display unsupported charts MapWindow and StreetViewWindow in menu

### PR DESCRIPTION
**Pull request by antoniusriha**

### CODE REVIEW

**Comment by liversedge** [comment]
You have misunderstood what nowebkit means.

**Comment by antoniusriha** [comment]
My understanding is that NOWEBKIT indicates that QWebView and other WebKit classes are not available. Since the classes MapWindow and StreetViewWindow depend on those classes, it doesn't make any sense to display the respective entry in the menu for them. Currently with NOWEBKIT defined empty GcChartWindow objects are displayed.
Could you please explain what my misconception of this is?

**Comment by liversedge** [comment]
It means QWebKit is not to be used, QWebEngine is used instead.
This is early support for QWebKit deprecation.

**Comment by antoniusriha** [comment]
Ok, thanks for the clarification!

On Oct 31, 2016 9:03 AM, "Mark Liversedge" <notifications@github.com> wrote:

It means QWebKit is not to be used, QWebEngine is used instead.
This is early support for QWebKit deprecation.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GoldenCheetah/GoldenCheetah/pull/2163#issuecomment-257234073>,
or mute the thread

**Pull request closed without merging**
