### PR TITLE
Issue 3373: FixGps to run on altitude alone.

### PR DESCRIPTION
**Pull request by ericchristoffersen**
Also prevent lots of mac build warnings by nulling the silent debug macros in geometrictools header.

### CODE REVIEW

**Comment by ericchristoffersen** [comment]
#3373

**Comment by ericchristoffersen** [comment]
Was failing to smooth high frequency noise. Need to be able to specify variance threshold lower than 1. Changed outlier spinboxes from QSpinBox to QDoubleSpinBox.

Original slope data:

precisionnoise

After smoothing with 0.01 outlier variance (and degree 20):

fractionalvariance

**Comment by ericchristoffersen** [comment]
Any objection? Someone take a look? Thanks.

**Comment by amtriathlon** [comment]
Hi Eric, the feature is interesting, but I think it is not intuitive for users to have it as an option for Fix GPS when there is no GPS data. May be Fix Elevation is a better place for this?

**Comment by ericchristoffersen** [comment]
> Hi Eric, the feature is interesting, but I think it is not intuitive for users to have it as an option for Fix GPS when there is no GPS data. May be Fix Elevation is a better place for this?

It could be. The filtering is pretty complex, you really need the stats and the test button in order to find a good choice. When filtering location data the altitude filtering needs to be available here as a first pass. It needs to be taken into account before smoothing the actual location spline. The combined stats really help.

I agree discoverability is a problem. I think it'd be ugly and unfortunate to put the altitude smoothing in two places. Was frustrating for me in a few cases where this altitude-only ability wasn't possible.

How about we rename "FixGps" into "Filter Route Data"/"Repair Route Data" something like that?

The FixElevation is a very different sort of repair because it queries a map service's opinion. In the many cases the internet map data is the source of the noise that needs filtering.

Maybe Fix Elevation should be renamed to something like "Repair Route using Map Service."

I dunno... I'm all ears let me know what you'd like.

PS: Other aspect of this change is to allow sub-integer variance. That was essential in order to smooth fine noise.

PPS: In a future checkin I'd like to change the use of variance in the ui to stddev. Much more stable and intuitive number. From math perspective they have the same capability but advantage of stddev is that it could actually have units for altitude. For location it wouldn't have a consistent unit because ECEF... :(

I'm waiting for this change to clear before I start that next one.

**Comment by amtriathlon** [comment]
Agree “Fix Route” may be a better name for the enhanced Fix GPS.
Also Fix Elevation could be renamed, since what it does is to fetch elevation from an external service, just “Fetch Elevation” could work, the source likely be explained in description.
This is just my opinion, I prefer @liversedge to have the last word on this.

**Pull request merged**
