### PR TITLE
Added ScriptContext for R/Python APIs called from DataFilter scripts

### PR DESCRIPTION
**Pull request by amtriathlon**
Carry RideItem, Specification and Metrics to consider the case when
the script is part of a UserMetric.
Python series, activityWbal and activityXdata honor RideItem and Specification,
allows them to be used in Scripts at UserMetrics and LTMPlot formulas
to obtaing the data points correspoding to the activity/interval.

### CODE REVIEW

**Comment by amtriathlon** [comment]
Python is complete for now and version number incremented, I will give a look to RTool adaptions.

**Comment by amtriathlon** [comment]
The changes to RTool seem simple, see the commit above, but there is an underlying problem: R API is not being called from Custom Metrics on computeMetrics, only when I use the Test button.

I'm using these 2 "My Duration" metrics for testing, one based on samples:

```
{
   value {

%%R
GC.result(length(GC.activity()$time))
%% ;

   }
}
```

and the other based on Metrics:

```
{
   value {

%%R
GC.result(GC.activity.metrics()$Duration)
%% ;

   }
}
```

**Comment by liversedge** [comment]
Weird. Am now looking at it.

**Comment by liversedge** [comment]
Looks like scripts are being executed -- simplify to GC.result(20) in the script and it works fine.
I think there may be a reentrancy issue calling the GC.API in a thread ?

Looking deeper.

**Comment by liversedge** [comment]
Yes, this is a very interesting problem that may not be resolvable.

R insists its event loop is on the main thread, QT also has an event loop on the main thread.

They do not and cannot be meshed. As a result the R API call back to the main thread is blocked by the QT event loop.

For now, I would remove Rscripting in user metrics. The only way around this is to place R in a separate process and interact with it in the same way Jupyter notebooks do it.

Make sense?

**Comment by liversedge** [comment]
actually, i can get this to work, so long as I don't call an API from an API call

this works for me:
```
{
    value { 
%%R 
df <- GC.activity.metrics()
GC.result(df$TSS) 
%%;

 }
}
```

**Comment by amtriathlon** [comment]
Hi Mark, it doesn't work for me that way either.
The behavior I'm seeing is the same with or without nesting of API calls:
- recomputing the metric after doing a Test takes the value of the Test for all activities and intervals
- quit, remove RideDB.json and restart the metric value is zero for all activities and intervals
Adding debug code to RTool::result and RTools::activityMetrics seem to indicate they are never called from computeMetrics, only from Test button.

**Comment by liversedge** [comment]
Yes, oddly I am now seeing the same too. Perhaps I was mistaken.

For the sake of everyone's sanity I would just remove R scripting from DataFilters and make it python specific !

**Comment by liversedge** [comment]
No the issue is the call is being made in the wrong thread and R maintains its own stack frame, so this is just corruption of memory structures.

We could use signlals/slots to call  the interpreter and return values across threads but tbh, its a lot of work that will probably break. I still think its easier to remove support for R scripts in data filters.

**Comment by amtriathlon** [comment]
Ahh, that’s makes sense but it’s a PITA. Thanks for the explanation!
I will close this PR and will create a new one for Python only plus the removal of R Scrits in DataFilter.

**Pull request closed without merging**
