### PR TITLE
Refactor of HrPw code FR > EN

### PR DESCRIPTION
**Pull request by AartGoossens**
Some variables names were in French. To improve readability and consistency I refactored these and some comments from French to English.
Also minor:  Added `.swp` (VIM swap file) to `.gitignore`.

### CODE REVIEW

**Comment by liversedge** [comment]
If you work in QTCreator you can refactor names quickly... 
The build fails coz you missed some bits. If you fix it up I'll pull it in.

THANKS!

**Comment by AartGoossens** [comment]
Hi @liversedge can you point to what I missed? Do any other files have dependencies on the method names I changed?

**Comment by liversedge** [comment]
the link here to travis has the build log?

**Comment by AartGoossens** [comment]
Ah I missed the part that I could view the details of the build... :) I will fix the issue(s)!

**Comment by AartGoossens** [comment]
@liversedge Fixed the issue, builds succeeded now.

**Pull request merged**
