### PR TITLE
Position tile config menu

### PR DESCRIPTION
**Pull request by paulj49457**
This PR matches the functionality in the Editable metadata tile https://github.com/GoldenCheetah/GoldenCheetah/pull/4519 to position the popup menu close to the location from which it was launched.

### CODE REVIEW

**Comment by amtriathlon** [comment]
This change looks problematic on Windows since the dialog gets positioned mostly out of screen for tiles near the borders:

image

I don't think this is a good idea.

**Comment by paulj49457** [comment]
@amtriathlon Please see updated version which ensures the dialog remains within the GC window.

**Comment by amtriathlon** [comment]
Yes, Paul, it seems to work on Windows now, I have not test on Linux or macOS.
My concern is: while I understand it may be convenient to reduce mouse movement, I am not sure we should micro-manage this instead of just let the Windows Managers do their job. 
A priori I am not willing to merge this, but If others better versed than me on UX have an opinion, I would like to read it.

**Comment by peret2000** [comment]
On Ubuntu 24.10 it works well. Menu is always visible and close to the tool icon.

**Comment by amtriathlon** [comment]
I will merge this so it can be tested together with https://github.com/GoldenCheetah/GoldenCheetah/pull/4519, we can revert if necessary. Thanks Paul.

**Pull request merged**
