### PR TITLE
Autoimport - new configuration option(s)

### PR DESCRIPTION
**Pull request by Joern-R**
... select only files for import which are CREATED or LAST_CHANGED in the file system during last 90/180/360 days
... thus limiting the number of files which are considered for import in the source directory
   (without changing/deleting the source files - and without the need to track indexes,...
    of what has already been imported).

### CODE REVIEW

**Comment by liversedge** [comment]
wouldn't it be better just to keep a record of the imported files and ignore files that have been previously imported ?

**Comment by Joern-R** [comment]
Agreed - was thinking on a record of imported files as well. But this may get more complicated when e.g. trying to substitute a file with a new version of the same training. What would be the "object" to track to find out if an activity is already imported. And has to be added in various place - e.g. also when deleting,... - what happens if a user delete via OS - is the record self-reparing,...

Obviously easiest could be "date/time" of the activities - which would provide a good match for most cases. So this solution may only be an iterim one - until such index is available.

**Comment by liversedge** [comment]
Given it would only affect automatic importing there is no harm in not autoimporting a file once it has been imported before. the user can always select it manually as they do today ?

I think the list would be global though, since once it has been imported for one rider it should be ignored for all others ?

**Comment by amtriathlon** [comment]
What about to put an additional field for the original file name in the .json to avoid having another file to maintain? The ride cache could generate the list or test the existence.

**Comment by liversedge** [comment]
Yes. We could add a metadata field "Import Filename" and get it from the metadata tags stored in the RideItem. When constructing the ride cache we could extract these into a stringlist too.

**Comment by liversedge** [comment]
mind you, that wouldn't be global...........

**Pull request merged**
