### PR TITLE
Fix 3712: Simulated Speed setting now honored in Ergo Mode.

### PR DESCRIPTION
**Pull request by ericchristoffersen**
#3712

### CODE REVIEW

**Comment by amtriathlon** [comment]
Settings label should be changed accordingly: https://github.com/GoldenCheetah/GoldenCheetah/blob/983874d59963c05c06e8c4a4a2df69aad3a381da/src/Gui/Pages.cpp#L738

**Comment by caronl** [comment]
Pretty clean solution @ericchristoffersen! Haven't tried the feature yet but I am imagining the fix would do exactly what I had in mind. As long as the label is adjusted accordingly (something like "Use simulated Speed in erg and slope modes") I think that solves it. Thanks! Can't wait to try the next build :)

**Comment by amtriathlon** [comment]
There is another place which also refers to "slope mode": https://github.com/GoldenCheetah/GoldenCheetah/blob/af19f31b245014881e46d13454c424c9449c9624/src/Gui/Pages.cpp#L1075
From that text only the first line is displayed on Windows, but on Linux it looks crammed: 
VirtualBicycleSpecifications
This would need some reformat or to move the additional text to a tooltip

**Comment by ericchristoffersen** [comment]
Thank you for checking Ale. Good catch. I messed with layout a bit, changed text, etc. Here is with latest. Now I'm sort of thinking to swap the left and right columns.

image

**Comment by ericchristoffersen** [comment]
Noooo... I didn't update the pull yet...

I guess I resync, make new branch, new pull, etc?

I think its better with the swapped columns:

image

**Comment by ericchristoffersen** [comment]
Ok, the latest commit has the last layout I posted above - moved the mass column to the right and fixed typos in some tooltips.

**Comment by amtriathlon** [comment]
Yes, I thought it was ready from your picture.
It doesn't scale too well when the window is not tall enough, which is weird because it happens even when the column has free space at the bottom. If you want to update, please make a new PR.

**Comment by ericchristoffersen** [comment]
Ok, made #3714 with the change to pages.cpp.

**Comment by caronl** [comment]
Feature works exactly as imagined in the first place. Love it! Kudos @ericchristoffersen

**Pull request merged**
