### PR TITLE
Qt6: adapt build system to accept Qt6

### PR DESCRIPTION
**Pull request by andreasbuhr**
Adapts the build system to accept Qt6.
It accounts for webengine rename to webenginequick.
It further drags in qtcore5compat, which provides QRegExp,
QXmlInputSource, and QXmlSimpleReader. Those classes are not
part of Qt6, but they are provided in qtcore5compat to reduce
the porting effort in projects like GoldenCheetah.

Of course, this should not be merged before really moving to Qt6.

### CODE REVIEW

**Comment by liversedge** [comment]
curious to know if you have got it building on Qt6.2 beta?

**Comment by andreasbuhr** [comment]
No, not yet. Expect another 10-20 pull requests. And so far it is all untested. Testing can start once it compiles. Biggest issue for me is currently the qwt upgrade. I fail to upgrade it because of https://github.com/GoldenCheetah/GoldenCheetah/issues/3929 .

**Comment by liversedge** [comment]
Its a local modification to qwt_plot_curve to fill under the curve using colors.
See 95901aa1e2b70db41bd421b7b60e8d3d8375e674

**Comment by liversedge** [comment]
FWIW am appreciative of what you are doing and will pay closer attention later -- especially if you get a build with 6.2 running !

CHEERS
Mark

**Pull request merged**
