### PR TITLE
Issue 3320: FixGPS: Route Smoothing and Multipass Outlier Removal

### PR DESCRIPTION
**Pull request by ericchristoffersen**
Update fix gps to support outlier removal.

### CODE REVIEW

**Comment by ericchristoffersen** [comment]
Hang on, I'm going to update this with the full route smoothing business.

**Comment by ericchristoffersen** [comment]
Added an optional final processing that smooths route in xyz. Altitude and route smoothing both now support multipass smoothing where outliers are discarded on first pass.

**Comment by liversedge** [comment]
is this now ready for merge?
IIRC a previous update crashed when set as a dataprocessor, have you fixed that?

**Comment by ericchristoffersen** [comment]
This change is working great. Import works, no crash.

**Comment by amtriathlon** [comment]
Fixed https://github.com/GoldenCheetah/GoldenCheetah/issues/3320

**Pull request merged**
