### PR TITLE
travis/linux: set QTWEBENGINE_DISABLE_SANDBOX=1

### PR DESCRIPTION
**Pull request by MeisterP**
There is an issue with qtwebengine (chromium) and glibc 2.34

See: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/374204
Fixes: https://github.com/GoldenCheetah/GoldenCheetah/issues/4196

### CODE REVIEW

**Comment by MeisterP** [comment]
Hmmm, I was hoping `[publish binaries]` would trigger a travis build as well for people to test the appimage. But doesn't seem to work.

**Comment by amtriathlon** [comment]
Travis builds are disabled for PRs due to credit restrictions, you can enable Travis in your fork and remove the first line in .travis.yml to trigger a build on master push

**Comment by MeisterP** [comment]
Generated an Appimage for testing locally with:

```bash
~$ wget http://goldencheetah-binaries.s3.us-east-1.amazonaws.com/Linux/GoldenCheetah_v3.6-DEV_x64.AppImage
~$ chmod +x GoldenCheetah_v3.6-DEV_x64.AppImage
~$ ./GoldenCheetah_v3.6-DEV_x64.AppImage --appimage-extract

~$ ls -l squashfs-root/AppRun 
lrwxrwxrwx 1 administrator administrator 13 Mai  8 08:00 squashfs-root/AppRun -> GoldenCheetah
~$ rm squashfs-root/AppRun

~$ cat >squashfs-root/AppRun <<EOF
#!/bin/bash
HERE="\$(dirname "\$(readlink -f "\${0}")")"
export QTWEBENGINE_DISABLE_SANDBOX=1
exec "\${HERE}/GoldenCheetah" "\$@"
EOF
~$ chmod +x squashfs-root/AppRun

wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
~$ chmod +x appimagetool-x86_64.AppImage

~$ ./appimagetool-x86_64.AppImage squashfs-root
```

it's available here:
https://github.com/MeisterP/GoldenCheetah/releases/download/testing/GoldenCheetah-x86_64.AppImage

**Comment by amtriathlon** [comment]
Thank you!

**Pull request merged**
