### PR TITLE
HRV Measures - Part 3

### PR DESCRIPTION
**Pull request by amtriathlon**
Added HRV fingerprint to RideItem to trigger refresh when
HRV Measures change.
Part of #2568

### CODE REVIEW

**Comment by rgeorge1985** [comment]
Ale,

I saw that the new Dev build is out, but is there an exe to install? I've never built from source nor have experience.

**Comment by amtriathlon** [comment]
Binaries for Windows, Mac and Linux will be attached there when available, in the next days, just like all the previous dev builds.

**Comment by rgeorge1985** [comment]
Thank you. Downloaded it. Should I uninstall dev v1705 first? With the
v1708, I'm not finding anything new in the interface. Can I assume it's
conflicting with the older version?

Also, importing polar r-r native files with the Get Measurements HRV isn't
working as it's not locating the file saved in the directory. The file is a
text file, coverting to .csv returns a header error.

**Comment by amtriathlon** [comment]
Please see the wiki and use the forum for usage questions, thanks.

**Comment by rgeorge1985** [comment]
Ok. Please see forum.

-Ronnie

**Pull request merged**
