### PR TITLE
Add telemetry for time to next erg point

### PR DESCRIPTION
**Pull request by mark-inderhees**
This adds a new workout telemetry to see the time to the next erg point. This will allow the user to see how much time is remaining at the current erg point value. This is useful to see how much longer the user must pedal at the current target power.

### CODE REVIEW

**Comment by mark-inderhees** [comment]
Sounds good. I'll make the change to remove nextPoint.

**Comment by mark-inderhees** [comment]
@liversedge Can this be merged into master or do I need to complete more steps? I'm not familiar with the commit process.

**Comment by mark-inderhees** [comment]
Cool, thanks!

**Comment by amtriathlon** [comment]
When nextPoint was removed and changed by rightPoint was this tested again?

It doesn't seem to work except for the first section, but I don't know yet if rightPoint behavior changed after this commit.

**Pull request merged**
