### PR TITLE
Add ANT+/BTLE serial number and antid into the device info.

### PR DESCRIPTION
**Pull request by cleeland**
Also added a poor-man's abstraction similar to `std::optional<>` that avoids messy `if` clauses that have to intuit whether something is set based on the values.  If you'd prefer using `std::optional<>` I can rework.

Work originally motivated by https://groups.google.com/g/golden-cheetah-users/c/LWhXNiLuS3k/m/3AChbB0-EAAJ

### CODE REVIEW

**Comment by amtriathlon** [comment]
Regrettably the highest possible value is also used to indicate serial number is not available for some sensors, that’s the reason for the test in https://github.com/GoldenCheetah/GoldenCheetah/commit/8c5b416b56c34a0cedb1481825156800e18a6f2d, removing that will include lot of invalid serial numbers, I would suggest to do some tests with the fit files in tests folder.

**Comment by cleeland** [comment]
Are there unit tests for FitRideFile, or do I test simply by building the whole app and importing a fit file?

The code in 8c5b416 appears to just check that the value is within (0, max) of uint32, basically excluding 0 or max as values.  This implies that there are devices that bother to add bogus values to the DeviceInfo record?

**Comment by amtriathlon** [comment]
> Are there unit tests for FitRideFile, or do I test simply by building the whole app and importing a fit file?

No, yes.

> The code in [8c5b416](https://github.com/GoldenCheetah/GoldenCheetah/commit/8c5b416b56c34a0cedb1481825156800e18a6f2d) appears to just check that the value is within (0, max) of uint32, basically excluding 0 or max as values. This implies that there are devices that bother to add bogus values to the DeviceInfo record?

That's what I found testing files, I don't know the reason.

Besides that, which would be the motivation for the change in the way serial number is handled, just to refactor the code?

**Comment by cleeland** [comment]
> which would be the motivation for the change in the way serial number is handled, just to refactor the code?

When I originally made this change, `serial` was not a uint32, but an int, with a default value of -1 as an overloaded value to indicate "there is no serial value".  That seemed clumsy and error-prone, so I replaced it with an abstraction that encapsulates what we really want to know which is "did this ever get set?".  That abstraction could be extended to contain a range of valid values, or (better) a lambda for value validation.

Any change you remember which `.fit` file had the bogus values?

**Comment by amtriathlon** [comment]
That changed was motivated by this thread since ID was being filtered: https://groups.google.com/d/msg/golden-cheetah-users/2Bm8NgBGtlQ/CCAKWnAtDAAJ

**Comment by cleeland** [comment]
Thanks for the link to that thread.  I don't see the file that's attached to that thread anywhere in the `test/rides` directory, so I will add it.

My change was motivated by this thread: https://groups.google.com/g/golden-cheetah-users/c/LWhXNiLuS3k/m/3AChbB0-EAAJ

**Comment by amtriathlon** [comment]
> My change was motivated by this thread: https://groups.google.com/g/golden-cheetah-users/c/LWhXNiLuS3k/m/3AChbB0-EAAJ

So you were referring to the previous version, that request is fulfilled in current master.

**Comment by cleeland** [comment]
I'm not sure why you closed this, because the two changes, while similar, achieve different things.  There are two different fields that can be in a FIT file, and they can both appear.  One is the serial number, while the other is the ant ID.  They can be different values, too.

The change in this PR properly adds the ANT ID when that field appears in the device info record.

**Comment by amtriathlon** [comment]
Let me be more explicit, this PR has one commit doing 3 separate things:
1) It supposedly fixes a bug the way serial is handled without proving it is one with a sample activity
2) It adds a feature (import antid) without providing a compelling use case
3) it refactors the code in a non-separable way, violating https://github.com/GoldenCheetah/GoldenCheetah/wiki/Guidelines-for-submitting-a-patch

**Comment by cleeland** [comment]
Thanks for the clarification on the feedback related to this.  I will address all of them.

**Pull request closed without merging**
