### PR TITLE
Support Multisport Fit Files

### LINKED ISSUE #3211: Importing Garmin multisport fit files produces a single activity
Importing a multisport fit file produced by a Garmin device causes GC to create only a single activity that has a wrong _Sport_ Tag. It gets the tag of the last extracted session. For Triathlons this is a _run_ activity.
This in turn leads to wrong analysis/metrics/...

This was already implemented and merged, see https://github.com/GoldenCheetah/GoldenCheetah/pull/1397.

The expected behavior is that GC splits the sessions included in a single multisport file into several activities.
Best case would be that there is a mechanism that allows to link them together.

### PR DESCRIPTION
**Pull request by thebaron06**
This patch series will introduce support for splitting multisport fit files into their contained single sport activities. Eg. a multisport recorded triathlon file will split up into 5 files:
 - swim
 - transition
 - bike
 - transition
 - run

Laps and XData are adjusted and appended too, if present.

Note:
 - Recording devices are merged throughout the parsing process and therefore the whole set of devices will be appended to each session split.
 - This will change the default sport/subsport of activities because otherwise it is just guessing and will influence metrics calculation. The default changed to generic.

Fixes #3211
Note: #3212

### CODE REVIEW

**Comment by liversedge** [comment]
I agree with Ale- do not use standard tags for specific purposes. By all means create a new one

**Comment by thebaron06** [comment]
As requested the change was squashed into a single commit, at least the multisport part.
I added another commit that belongs to the XData classes and allows for deep copies. This one is sepperated.

The change now remove the debug output, introduces a new Tag called _BaseFileName_ that should represent the base filename the multisport activity is split from.

Device info is split too.

But I do not understand what you mean with the following
> the change of source filename tag to anything different from that

**Comment by amtriathlon** [comment]
Please ignore the comment bout source filename, the mangling I was referring to is done by RideFileImport, not your code.

**Comment by thebaron06** [comment]
I exported a couple of years of fit files from my archive and other platforms and all names have been unique across ~3k filenames given them by different Garmin devices.
But I fully agree that one shouldn't rely on this to be unique.

The aim of setting the tag was not to uniqually identify sthg. It was ment to display the fact that this activity originates from a multisport file and to have some kind of relationship between the activities that are part of the series.
If there is a better way to do this I will be happy to add this.
Is there another proposal to display that this ?

Btw. Data info is now splitted too. Have you spotted any other data that is candidate to be split up?

**Comment by amtriathlon** [comment]
>The aim of setting the tag was not to uniquely identify sthg. It was ment to display the fact that this activity originates from a multisport file and to have some kind of relationship between the activities that are part of the series.

Yes, I agree, but being that identifier unique makes it easier to get all the components of a multisport activity with a simple filter.

>If there is a better way to do this I will be happy to add this.
Is there another proposal to display that this ?

The start date in ISO format is a good candidate, it is warranted to be unique in GC.

>Btw. Data info is now splitted too. Have you spotted any other data that is candidate to be split up?

No, all data and metadata seem to be ok as far I have tested.

**Comment by thebaron06** [comment]
> > The aim of setting the tag was not to uniquely identify sthg. It was ment to display the fact that this activity originates from a multisport file and to have some kind of relationship between the activities that are part of the series.
> 
> Yes, I agree, but the uniqueness of this multisport ID would make it easier to get all the components of a multisport activity with a simple filter, without the need to look for collisions.

I agree on that too.

> > If there is a better way to do this I will be happy to add this.
> > Is there another proposal to display that this ?
> 
> The start date in ISO format is a good candidate, it is warranted to be unique in GC and readily available.

Thanks for the hint. The latest version uses this to identify files that belong together by their origin.

> > Btw. Data info is now splitted too. Have you spotted any other data that is candidate to be split up?
> 
> No, all data and metadata seem to be ok as far I have tested. Good job!
Thank you for your review and continuous work on this great project, too.

As mentioned above, the idea is to add a new Tag - _Multisport_. The presence of this tag indicates that there have been several sessions splitted from an single activity file. The value of this tag is the ISO formatted start time of the base file the sessions originate. This should allow for filtering/grouping files that belong together.

**Comment by thebaron06** [comment]
Just saw that I forgot to add the above mentioned code segment. Will fix this later.

**Pull request merged**
