### PR TITLE
french translation partial update

### PR DESCRIPTION
**Pull request by vlcvboyer**
I changed directly in gc_fr.ts file after updating it with lupdate
Is it the expected way to do it or is it mandatory to use qt software to edit this file?

### CODE REVIEW

**Comment by vlcvboyer** [comment]
Hi
Can you please review and merge?
...there is still a lot of text to translate but I want to ne sure that I'm doing it in a suitable way!

**Comment by grauser** [comment]
Could you contact me directly ?
Thank you.

**Comment by vlcvboyer** [comment]
... yes... how to do that? can't see your email !

**Comment by vlcvboyer** [comment]
Does my new commit match your expectations?

**Comment by grauser** [comment]
Yes, thank you.

**Pull request merged**
