### PR TITLE
Improve on import from polar hrm files

### PR DESCRIPTION
**Pull request by leifwar**
I've made some changes to ease the import of polar hrm file into Goldencheeta. There are two main contributions:

1: Add polar created gpx file if it exist (always with the same name as the .hrm file). 
2: Handle R-R data if this is the only data that has been recorded. I sometimes turn of everything but the R-R recording in which case it will store this instead of the normal heart beats per minutes.

### CODE REVIEW

**Comment by liversedge** [comment]
Would it be better to store the R-R data in its own data series ?

**Comment by liversedge** [comment]
We can add a new series quite easily.... then with the formula work I am doing it could be plotted without any code changes.

Do let me know what you think.

**Comment by leifwar** [comment]
I agree with you that it would be much better to store the R-R data in its own data series. I did think about doing that but didn't know how or how that would fit with the rest of the code.

**Comment by liversedge** [comment]
Its ok, I will commit this and then come back and add RR as a data series later.

THANKS FOR THE CONTRIBUTION :)

**Comment by liversedge** [comment]
Can you email me your name so I can add you to the contributors list ?

Ta
Mark

**Comment by leifwar** [comment]
My name is Leif Warland. 

----- Opprinnelig melding -----

Fra: "Mark Liversedge" <notifications@github.com> 
Til: "GoldenCheetah/GoldenCheetah" <GoldenCheetah@noreply.github.com> 
Kopi: "leifwar" <leif.warland@getmail.no> 
Sendt: 28. august 2015 20:15:31 
Emne: Re: [GoldenCheetah] Improve on import from polar hrm files (#1543) 



Can you email me your name so I can add you to the contributors list ? 

Ta 
Mark

**Pull request merged**
