### PR TITLE
Basic ANT FE-C support

### LINKED ISSUE #1393: Add support for ANT FE-C profile (a.k.a. fitness equiment controls / trainer resistance)

### PR DESCRIPTION
**Pull request by stschake**
This adds basic support for ANT FE-C trainers. Reads power, cadence and speed from trainer and relays load setpoint back.

This partially fixes #1393

### CODE REVIEW

**Comment by liversedge** [comment]
Have put this into the v4.0 queue as its quite a significant update and we're feature frozen in v3.2.
This is great stuff, which device is it tested against ?

**Comment by stschake** [comment]
I tested this with a Tacx Vortex Smart trainer. Apart from another Tacx model, I don't believe there are other trainers with FE-C out there yet.

**Comment by vlcvboyer** [comment]
Can you please explain differences between:
Basic support for Tacx Vortex trainers #1213
and
Basic ANT FE-C support #1448

I've just upgraded my Smart Vortex firmware. When including your commits both are detected "Fitness Equipment Control" and "Tacx Vortex Smart". Which one do you recommend to choose?
Do we have to select FE-C only, Vortex only or do we have to connect both? Maybe power (also detected) has also to be selected?

**Comment by stschake** [comment]
#1213 was to support the Tacx propietary ANT protocol. This one #1448 is to support the new FE-C standard by the ANT consortium, which can possibly be used with trainers from any manufacturer (once they add support for it).

The trainer will always broadcast the Tacx protocol, the FE-C one (once you upgraded the firmware), and the power and cadence protocols. The last two are only so you can show and record power and cadence/speed on your Garmin for example, they do not allow setting the trainer resistance. For that you can either use the Tacx one (Tacx Vortex Smart) or the FE-C (Fitness Equipment Control).

The simple answer is that if you have upgraded your Vortex trainer, you can just connect Fitness Equipment Control. This will give you power, speed, cadence and resistance control through GC (wattage).

**Comment by vlcvboyer** [comment]
FYI I've worked today on ANT FE-C protocol
I used your contrib as basis and started implementation of additional features such as simulation mode (slope & wind), etc. 
(https://github.com/vlcvboyer/GoldenCheetah/tree/ant-fec)

**Comment by vlcvboyer** [comment]
Hi,
I want to release my additions to this contribution from stschake.
How do you want me to do it as my contribution is based on another fork not merged.
Can I create a pull request based on another fork?

**Comment by stschake** [comment]
With cf7b4863471aa887bdb75d4f1b88401fb1ae56c2, this can be closed.

**Comment by liversedge** [comment]
Thanks Stefan, I will make sure you get the credit in the release notes !
Between you and Vianney this is a major new feature and brings in support for a wide range of electronic trainers.

THANKS

**Pull request closed without merging**
