### PR TITLE
New cloud provider - Azum

### PR DESCRIPTION
**Pull request by DanielZelei**
This pull request is for adding new cloud service provider - Azum (https://www.azum.com/en/)

Implementation was based on https://github.com/GoldenCheetah/GoldenCheetah/wiki/Using-the-Cloud-Services-API and also checking how others providers are implemented it previously.

OAuth, Download and Query capabilities are used for the service. Client id is hard-coded, secret will be shared with the GC build team (please let me know how I can do it.)

image

image

image

### CODE REVIEW

**Comment by danielboros1990** [comment]
@amtriathlon @liversedge can you please merge this?

**Comment by amtriathlon** [comment]
> @amtriathlon @liversedge can you please merge this?

No, I can't . At this stage of the release cycle my GoldenCheetah work is oriented to fix bugs, complete partially implemented features, documentation and support.

**Comment by liversedge** [comment]
I am merging on the understanding that the developers at Azum will provide any support required

**Comment by amtriathlon** [comment]
I added the secret for AppVeyor builds in https://github.com/GoldenCheetah/GoldenCheetah/commit/392ec2a74aa756dbd98af3f50157e89a4b229ab7, the generated installer can be downloaded for testing from: https://ci.appveyor.com/project/Joern-R/goldencheetah-knhd8/builds/46486634/artifacts
Regrettably the secret is too long for travis encrypt, so we will need a shorter one for macOS and Linux builds.

**Comment by DanielZelei** [comment]
@amtriathlon 

Thank you for merging. Tomorrow I will share another secret via email.

**Pull request merged**
