### PR TITLE
Swedish translation

### PR DESCRIPTION
**Pull request by henolo**
various corrections of spelling etc

### CODE REVIEW

**Comment by amtriathlon** [comment]
Hi Henrik, could you rebase this to merge just one commit with all the Swedish translations changes?

**Comment by liversedge** [comment]
Hi Henrick, any news on rebasing?

Would be ace to apply your update.

**Comment by henolo** [comment]
Thanks for your patience!!

Still digesting https://git-scm.com/book/en/v2/Git-Branching-Rebasing
and it appears very easy to get lost...

You mean "removing" the "merge-remote" commits and sqashing the "real" commits into one?

Appear to be possible to do this with interactive rebase tool, will try this.

**Comment by henolo** [comment]
Succeeded to create a single "useful" commit locally, Tried git push but get error messages about "tip of your current branch is behind its remote counterpart".  Will "--force" help??

**Comment by amtriathlon** [comment]
Hi Henrik, once you have your commit history clean you can do a forced push.
In this case a simple way to do this is to save your gc_sv.ts file in another folder, use git reset --hard to go back to the point when your history diverges (the commit before this https://github.com/GoldenCheetah/GoldenCheetah/pull/2282/commits/7b1b8e5e33ebc602ab17e1dd7d355dc16ae1130e, I think), use git pull upstream master to update your local repository, copy back your saved gc_sv.ts, commit the changes and to a git push --force origin master

**Comment by henolo** [comment]
I think that this really shouldn't be very complicated but still some things appears to elude me. At least things don't behave as I expect them to. 

To not stall, I attach file here. 
[gc_sv.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/726306/gc_sv.txt)

Will try to keep it simpler next time.

**Comment by amtriathlon** [comment]
I lupdated the file to include the newly added/changed strings and applied the change on your behalf to master, thanks for your contribution Henrik!

**Comment by gcoco** [comment]
Hi. I find the easiest way to do this is copy out the .ts file.
Create a new branch. Copy in the new .ts file and commit the change.
Then create a pull request from the new branch.
When the request has been pulled in you can delete the branch.

**Pull request closed without merging**
