### PR TITLE
C++11 conversion

### PR DESCRIPTION
**Pull request by bdb**
I'm opening this for comment and discussion. As it stands right now, I've enabled C++11 and fixed the few resulting errors. I also did a basic conversion for FitRideFile as an example. This was split into 2 commits (unique_ptr RAII and general C++11 semantics).

Note that this first pull request includes the commits from my other 'fix-bugs-and-warnings' request since some of those are required for C++11. So the actual C++11 changes begin with the 'Require C++11' commit.

### CODE REVIEW

**Comment by bdb** [comment]
Hmm, QWT3D is failing to link for the Qt5 build (though it links for the Qt4 build). Is that an installed library or built from source? (I don't have it installed/enabled locally.)

**Comment by liversedge** [comment]
I suspect ABI issues with c++11.

**Comment by bdb** [comment]
OK, odd that Qt4 job built and passed but not 5. I'll try to install it locally.

**Comment by liversedge** [comment]
I think QT4 builds it and QT5 doesn't. but not sure.

**Comment by bdb** [comment]
Ah, that would explain it. So the travis setup needs to change to build the library instead of installing a binary (from hombrew or somewhere?).

**Comment by liversedge** [comment]
Just checked and it is build from source for both.

**Comment by bdb** [comment]
Thanks. It probably needs to built as C++11 too for some reason due to Qt5 changes. I'll look into it tonight after work and workout.

**Comment by bdb** [comment]
OK, sorted it out, C++11 did not have to be enabled for the external libs, but libc++ did have to be used. Xcode 7+ defaults to that, I guess earlier versions do not.

I was thinking too; if you are interested in this, would it be OK to just require C++14. Not a big deal for Xcode and MSVC, but it would limit GCC to 4.9.2+. Generic lambdas, and move captures would be the big things and it would be nice to have auto return type too.

**Comment by liversedge** [comment]
Trolltech have announced that from QT 5.7 c++11 will be used by QT modules and will be mandatory -- so we should be ready for this in the next release (4.1 2017)

**Comment by liversedge** [comment]
Hi,

QT 5.6 now requires c++11 so we can start conversion, but we still need to support non c++11 compilers too.

Are there any changes in here that you feel warrant the effort ?

Cheers!

Mark

**Comment by bdb** [comment]
Conversion can be done piecemeal. This initial patch was just enough to get things going. However if you still have to support  non-C++11 compilers than I'm not sure what you are asking. Conversion is all-or-nothing, so GCC 4.8+, Clang 3.3+ and MSVC 2015 would be the minimum supported versions.

**Comment by liversedge** [comment]
Yeah I was on that page. It will need to wait for QT5.6 support across the board.

Thanks for the advice.

**Pull request closed without merging**
