### PR TITLE
Re-introduced vector expressions

### LINKED ISSUE #2278: Vector formulas don't work anymore in V3.4
Reported at the forum: https://groups.google.com/forum/#!searchin/golden-cheetah-users/vector%7Csort:date/golden-cheetah-users/WmUGbNHviJE/Gb-ZdXn-DwAJ

### PR DESCRIPTION
**Pull request by amtriathlon**
Using |Date_From:Date_To| instead of [Date_From:Date_To] to
avoid conflicts with array indexing
Fixes #2278

### CODE REVIEW

**Comment by liversedge** [comment]
We should avoid using | .. why not use [[ and ]] ?

**Comment by liversedge** [comment]
But also, thanks for re-introducing it !

**Comment by liversedge** [comment]
In terms of how we would do this -- the lexer should return something for '[[' and ']]' patterns.
e.g. LSB and RSB for left square bracket and right square bracket.

**Comment by amtriathlon** [comment]
I used | because it was simpler and it doesn't generate conflicts, but I understand | could be useful in the future, I will change for [[]] and push an update.

**Comment by liversedge** [comment]
thanks!

**Pull request merged**
