### PR TITLE
Settings: Inline-editing for Measures

### PR DESCRIPTION
**Pull request by thejockl**
* Implmented inline-editing in Measures-tab, similar to Zones (Power, HR, Pace)
* Disabled editing of columns Datetime, Source, Original-Source

image

### CODE REVIEW

**Comment by amtriathlon** [comment]
Hi Joaquim, it looks nice but it seems to be unusable when you have several years of daily data.

I had noticed athlete settings was slower after the Zones changes, but since zone tables are usually not to large it was usable.

Now after changing measures it takes several minutes to load and to switch between Body (12 years of daily data) and Hrv (7 years of daily data) when previous to this change it was instantaneous.

**Comment by thejockl** [comment]
Hi Ale, that is a clear blocker, probably caused by the QStyledItemDelegates. I will check if my implementation can be optimized.

My main concern is the space occupied by the edit-fields on top, allowing only some few visible rows in the list. Also thinking about your impressive amount of data, would it be helpful having a "real" tree, grouping the entries by year?

For the editing, I could make it work similar to the definition of these fields in the options, using a "Edit"-Button:
image

**Comment by amtriathlon** [comment]
> My main concern is the space occupied by the edit-fields on top

As you propose above, an Edit button (default for the selected item, and with double-click on an entry shortcut) would be a viable solution, you can re-use the Add dialog for that purpose. We use this pattern in other parts of the code.

> Also thinking about your impressive amount of data, would it be helpful having a "real" tree, grouping the entries by year?

Personally I would prefer to keep the list simple and efficient as it was before, it is not that common that I look at old data here, I use charts for that purpose.

**Comment by thejockl** [comment]
It seems the issue is caused by my naive implementation of DoubleSpinBoxEditDelegate::sizeHint which is called very often and creates a dedicated QDoubleSpinBox every time. The latest commit precalculates and caches the sizeHint. This improved performance massively in my testdriver (QTreeWidget with 8 columns / 10000 rows). With this change, inline-editing hopefully can be kept for measures, creating a unified UX for the settings.
Ale, if the performance improvement is good enough for you, I will add the same pattern to all delegates in src/Gui/StyledItemDelegates.

**Comment by amtriathlon** [comment]
> It seems the issue is caused by my naive implementation of DoubleSpinBoxEditDelegate::sizeHint which is called very often and creates a dedicated QDoubleSpinBox every time. The latest commit precalculates and caches the sizeHint. This improved performance massively in my testdriver (QTreeWidget with 8 columns / 10000 rows). With this change, inline-editing hopefully can be kept for measures, creating a unified UX for the settings.

Bingo! Now performance is much better, in fact I see no differences in perceived performance with current master.

>Ale, if the performance improvement is good enough for you, I will add the same pattern to all delegates in src/Gui/StyledItemDelegates.

Dialog start still takes 6-7 secs, likely due to this same issue in Zones, I will test again when you apply that change.

**Comment by thejockl** [comment]
Didn't implement sizeHint-precalculation for DirectoryPathDelegate as it requires runtime information (and it is not used in tables with too many rows)

**Comment by amtriathlon** [comment]
Thank you, athlete settings dialog shows much faster now, I will use this and merge the next week.
Let me now when you are done with these changes so I can trigger snapshot builds with updated translation files so translators can use the binaries for testing translations without the need to build from source.

**Comment by thejockl** [comment]
For now, this topic is fine for me. I will for sure jump back in when issues or questions arise

**Comment by amtriathlon** [comment]
This PR introduced a bug when adding new measures using Imperial units, it was reported in https://groups.google.com/g/golden-cheetah-users/c/hAwFNWP3-G0/m/-pgPYkhfAwAJ and I can reproduce it using weight as example.

**Pull request merged**
