### PR TITLE
Added SWIM XData for pool swims

### PR DESCRIPTION
**Pull request by amtriathlon**
One record per length with 3 fields:
TYPE: 0-pause, 1-free, 2-back, 3-breast, 4-fly, 5-drill, 6-mixed, 7-IM
DURATION: seconds per length
STROKES: total strokes per length
Related to #2010

### CODE REVIEW

**Comment by liversedge** [comment]
COOL!

**Comment by liversedge** [comment]
Do you have a fit file with swim data in it we can add to the tests directory?

**Comment by amtriathlon** [comment]
Mark, in test/rides folder there are already some fit files from pool swims:
AleV_Swim_2015-02-09-16-15.fit from a Garmin 910xt
GarminHRMswim.fit from a Garmin 920xt with HRMswim band
GarminSwimExample.fit from a Garmin Swim
lap_swim_test_FR920xt.fit from a Garmin 920xt
let me know if you need/want more.

**Comment by liversedge** [comment]
:+1:

**Pull request merged**
