### PR TITLE
Update tap for lmfit on Homebrew due to deprecation of homebrew/science

### PR DESCRIPTION
**Pull request by arunh**
As per title, this is needed to allow a clean install of lmfit.

### CODE REVIEW

**Comment by liversedge** [comment]
thanks!

**Comment by liversedge** [comment]
hi arun .. did you mean to include so many different updates in the same pull request?

**Comment by arunh** [comment]
Ah, sorry no - my bad - would you like me to re-create on a fresh branch and cherry pick just what you need?

**Comment by arunh** [comment]
Closing as incorrectly created from fork master. Use #2761 pull request for same fix instead.

**Comment by liversedge** [comment]
When you're ready looks like 3 updates;
python
searchbox
travis?

**Pull request closed without merging**
