### PR TITLE
Fix VLC Hangs with Intentional State and Ordered Async Dispatch

### PR DESCRIPTION
**Pull request by ericchristoffersen**
Fix for #3756:

Two main parts to this change.
- a thread locked managed player state
- all calls to VLC are now made via an ordered Async dispatch.

Probably the ordered async dispatch is the more important of
the two as it moves calls to vlc stop() off the gui thread.

Tested by repetitively seeking and stopping on 50+ virtual rides on windows 10 with vlc 3.9.0 and 3.10.0.

Zero hangs in three days of trying.

### CODE REVIEW

**Comment by ericchristoffersen** [comment]
This creates and destroys threads all the time which is rude. I am redoing with a threadpool.

**Comment by ericchristoffersen** [comment]
Modified so instead of chaining futures it now runs everything on a traditional queue processed by a worker thread.

**Comment by Sigfreid74** [comment]
I've tested this change the skipping fwd / bwd in rlv video is definitely more responsive. No hangs so far.

**Comment by human705** [comment]
I've been testing this for about a week with no issues.

**Comment by Sigfreid74** [comment]
I would love to see this improvement included soon as I'm having to use the current snapshot build which does not have this for the sake of Strava functionality and have gone back to having hanging VLC behaviour.

**Comment by amtriathlon** [comment]
Since this is change affects Linux and macOS builds it needs to be tested on these platforms before merging. All testing reported seems to have been done on Windows only, AFAIK.

**Comment by peret2000** [comment]
Ops! I did not realize those tests were expected...
So, I can tell my experience: I have been using that patch (merged into my own development fork, I have to say) and it seems to work nicely, on Ubuntu 20.10 (release and debug deliveries)
Maybe it was not the root cause of my problems, so I did not want to add 'noise': since december I was experiencing that videos froze, when synching with the ride, and updated frozen frames each few seconds. It was annoyning. I tried many changes: going back through thhe code, removing commits, etc, with no success.
Finally, merging with the branch of this pull request, the prooblem dissapeared, I have been using it for several weeks. So, although I was not convinced this was the solution, as I did not understand very well tha changes and the original problem, I would say that it has solved my issue; I am very happy.
And, anyway, it is not causing any trouble to the application; in my experience, it can be merged safely

**Comment by human705** [comment]
Can you please share the instructions you followed to build  on Ubuntu 20?

**Comment by peret2000** [comment]
I build on Ubuntu 16.04, and then deploy the binary another machine. I meant that the binary works fine on Ubuntu 20.10

**Comment by amtriathlon** [comment]
> Can you please share the instructions you followed to build on Ubuntu 20?

[INSTALL-LINUX](https://github.com/GoldenCheetah/GoldenCheetah/blob/master/INSTALL-LINUX) is now updated to build in Ubuntu 18.04, it should help to build on 20.xx, please use developers forum for questions if you found problems.

**Comment by mfkl** [comment]
FYI, LibVLC 4 introduces proper async stop, so this code may be removed in the future (when v4 goes stable).

**Pull request merged**
