### PR TITLE
fix builds with Bison >= 3.7, bump CI to Bison >=3.4

### LINKED ISSUE #3586: build fails with >=bison-3.7
Goldencheetah fails to compile after updating to >=bison-3.7 on Gentoo.
Bison 3.7 changes how header files are included [[1](https://lists.gnu.org/archive/html/info-gnu/2020-07/msg00006.html)][[2](https://www.gnu.org/software/bison/manual/html_node/_0025define-Summary.html)], in that instead of copying and inserting the contents of a file, the file itself is included (by default as '"basename.h"').

Gentoo Tracker bug is https://bugs.gentoo.org/737026
Probably the same issue on debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966704

```
x86_64-pc-linux-gnu-g++ -c -march=native -O3 -pipe -Wno-unused-variable -Wno-sign-compare -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DGC_WANT_PYTHON -DGC_VIDEO_QT5 -DGC_WANT_ROBOT -DQXT_STATIC -DSIP_STATIC_MODULE -DGC_HAVE_PYTHON -DGC_HAVE_ICAL -DGC_HAVE_LIBUSB -DLIBUSB_V_1 -DGC_HAVE_SAMPLERATE -DGC_HAVE_OVERVIEW -DGC_HAVE_GENERIC -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_WEBENGINEWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_CHARTS_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_WEBENGINE_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_QMLMODELS_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_SERIALPORT_LIB -DQT_POSITIONING_LIB -DQT_BLUETOOTH_LIB -DQT_CORE_LIB -I. -IANT -ITrain -IFileIO -ICloud -ICharts -IMetrics -IGui -ICore -IPlanning -I../qwt/src -I../qxt/src -I../qtsolutions/json -I../qtsolutions/qwtcurve -I../lmfit -I../levmar -IPython -Itrue/include -Itrue/include -Itrue/include -I/usr/include/libusb-1.0 -I/usr/include/python3.7m -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtMultimediaWidgets -I/usr/include/qt5/QtWebEngineWidgets -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtCharts -I/usr/include/qt5/QtOpenGL -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtWebEngine -I/usr/include/qt5/QtWebEngineCore -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtQmlModels -I/usr/include/qt5/QtWebChannel -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtConcurrent -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtPositioning -I/usr/include/qt5/QtBluetooth -I/usr/include/qt5/QtCore -I. -I/usr/include/libdrm -I/usr/lib64/qt5/mkspecs/linux-g++ -o DataFilter_yacc.o DataFilter_yacc.cpp
DataFilter.tab.c:152:10: fatal error: DataFilter.tab.h: No such file or directory
compilation terminated.
make[1]: *** [Makefile:32199: DataFilter_yacc.o] Error 1
make[1]: Leaving directory '/var/tmp/portage/app-misc/goldencheetah-3.6_alpha_p20200905/work/GoldenCheetah-6164dd963f154ce9a05661167b23c6c06b2649dd/src'
make: *** [Makefile:91: sub-src-make_first-ordered] Error 2

```

[build.log](https://github.com/GoldenCheetah/GoldenCheetah/files/5178234/build.log)

### PR DESCRIPTION
**Pull request by flokli**
Building GoldenCheetah currently fails in environments with more recent (>=3.7) versions of bison (Debian Sid, Gentoo, Fedora Rawhide, Archlinux). This can be developer machines, downstream distro packaging environments etc.

The fixes proposed here will make it build on all environments with at least Bison 3.4.

This includes the commits from https://github.com/GoldenCheetah/GoldenCheetah/pull/3590, but also bumps CI to use bison versions >= 3.4, and updates some documentation around bison versions.

We need to stay with Xenial for the reasons described in https://github.com/GoldenCheetah/GoldenCheetah/pull/3590#issuecomment-706731402, so we only install a later version of bison, but keep the base distro.

macos builds use `brew` to get a more recent version (and point `QMAKE_YACC` to it).

windows builds use the choco `winflexbison3` package (and set `QMAKE_LEX` and `QMAKE_YACC` to lookup from `$PATH`).

flex and bison are currently also shipped inside the GoldenCheetah/WindowsSDK zipfile (together with some custom build rules). To ensure we don't use these, I currently remove them after extracting from there.
In a followup bump of this tooling, these should probably be removed from the archive alltogether.

Closes #3586.

### CODE REVIEW

**Comment by MeisterP** [comment]
You updated most comments with bison >= **2.4** but I think you meant to write bison >= **3.4**

**Comment by flokli** [comment]
Backported to 20.09 in 87f329dfcc3f462227b72c6e09a5d2d2f0f012f0 and 1467c169ab9e40962283a8573fd17e6638abc482.

**Comment by michaelprager** [comment]
This PR needs slight adjustments, it conflicts with the changes to in travis/osx/before_install.sh from https://github.com/GoldenCheetah/GoldenCheetah/commit/94ccac5e0fe6c09323bb3efc32bff76c7cea163e

I noticed because this PR is used by the arch aur package golden-cheetah-git to make GoldenCheetah compile on arch.

**Comment by flokli** [comment]
[nixpkgs](https://github.com/nixos/nixpkgs) also ships these patches downstream to fix their builds.

IIRC, this so far wasn't merged as CI uses 16.04 to generate an AppImage, which is using a super old Bison version, and builds would break (https://github.com/GoldenCheetah/GoldenCheetah/pull/3590#issuecomment-706731402)

@amtriathlon , @liversedge: how does the situation look these days? Is CI on a more recent distro version these days?

**Comment by amtriathlon** [comment]
> @amtriathlon , @liversedge: how does the situation look these days? Is CI on a more recent distro version these days?

Currently CI builds use Windows 10, macOS 10.14 and Ubuntu 18.04, after v3.6 release we could consider going to more recent versions, but not before IMO.

WRT to downstream builds not using our CI scripts I would suggest to include https://github.com/GoldenCheetah/GoldenCheetah/pull/3628/commits/1e089e3abd270f86f6a00b66e608cd837c8e6430 only, CI changes are irrelevant in that case.

**Comment by flokli** [comment]
I rebased this to latest `master` - the conflict was fairly trivial.

I also opened https://github.com/GoldenCheetah/GoldenCheetah/pull/4119, which only contains https://github.com/GoldenCheetah/GoldenCheetah/commit/1e089e3abd270f86f6a00b66e608cd837c8e6430 (so doesn't update CI to a more recent bison version).

**Comment by flokli** [comment]
@amtriathlon merging in 1e089e3 only also doesn't work, as it'll break the windows CI.

**Comment by amtriathlon** [comment]
> @amtriathlon merging in [1e089e3](https://github.com/GoldenCheetah/GoldenCheetah/commit/1e089e3abd270f86f6a00b66e608cd837c8e6430) only also doesn't work, as it'll break the windows CI.

Obviously, we have discussed this before. My comment was oriented to people building downstream without our CI scripts.

**Comment by liversedge** [comment]
I would also add that adding QMAKE_MOVE=cp to gcconfg.pri solves the header filename issue

**Pull request closed without merging**
