### PR TITLE
Support Custom Virtual Power Curve

### PR DESCRIPTION
**Pull request by ericchristoffersen**
This is part 1 of issue 3408.

Implements all the math needed for custom power curve feature, then ports all current virtual curves in realtimetrainer to use new polyfit object.

Subsequent checkins will add ui to allow custom functions to be defined and used.

Added test function to pull in and compile the templates (not called.)

### CODE REVIEW

**Comment by ericchristoffersen** [comment]
Implemented dialog for adding virtual power curves.
Next step is to save and restore custom power fit as part of device.

**Comment by ericchristoffersen** [comment]
Dang. Tool disagreement about qualified typename... working on it.

**Comment by liversedge** [comment]
I get a SEGV

crash

**Comment by liversedge** [comment]
You can't dereference via the stack;
std::vector<int>&v={0,0,0,0}
is illegal.

**Comment by ericchristoffersen** [comment]
Hi Mark. Thanks for testing this. I am at a loss how I might deduce what the issue is.

I don't think the code above is illegal. The {0,0,0,0} is constructed to a std::vector temp, then a reference to that is assigned as a parameter of GetPolyFit. References to expression temps are permitted, but it is illegal to use that reference outside the lifetime of the expression.

As an example of what is being done above consider:

int foo(std::vector<int>&v){return v.size();}

It is certainly valid to call foo with:

foo({0,0,0,0});

The reference to the temp is fine.

I believe something else is happening here involving static init.

Can you tell me, is this a data access that is failing? Or is it failing on an indirect call instruction? It could be that the static function pointer array isn't initialized prior to this construction of the static predefinedPolyFit initialization.

How might I debug or at least repro this short of reproducing a linux build?

**Comment by liversedge** [comment]
It is in the screenshot?
It fails when the method is called (the next frame on the stack).
It is illegal and undefined to initialise references with a stack object, 
try compiling:
```std:vector<int>&v={0,0,0,0};```
Mark

**Comment by ericchristoffersen** [comment]
The screenshot says segfault. I think its because its an indirect call through null because the maker array hasnt been init yet.

I uploaded a new fix and think it is fixed now. There is a static init array of polyfit makers defined in polynomialregression.cpp. Then there is the static init array of predefined virtual trainers defined in realtimecontroller.cpp. They are in different compile units so theres no guarantee of their init order. I put the predefined trainer array into a function so isn't init until first use, it relies on the load time init of the polyfit maker array, which is fine. I also added back the constexpr to the polyfit construction but as a macro so it can be enabled in the future when were all using cxx17 tools. Constexpr will cause the maker array to live in the image with no runtime init.

Can you please give this update a try?

**Comment by ericchristoffersen** [comment]
Also, with your above example use const:

    const std::vector<int>& v = { 0,0,0,0 };

**Comment by liversedge** [comment]
Ah ok. Will do. But late here now but will check it out tomorrow. Cheers.

**Comment by ericchristoffersen** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/issues/3408

**Pull request merged**
