### PR TITLE
Function to control trainers with seperate powermeter

### PR DESCRIPTION
**Pull request by ragman1976**

### CODE REVIEW

**Comment by liversedge** [comment]
What is this pull request?

It looks like you need to rebase this.

**Comment by ragman1976** [comment]
Many trainers have an inaccurate power measurement. For somebody who has a accurate Powermeter on the bike it would be great to control the trainer with the Powermeter from the bike.
I guess PerfPro contain such a functionality for example.

**Comment by liversedge** [comment]
Your pull request is into a maintenance branch - it should be master
Can you resubmit for master and make sure it is rebased.

You might want to wait till next week as we are releasing 3.4 this weekend.

**Comment by ragman1976** [comment]
Ok. I´m not familiar with the "maintenance barnch-master system" at GitHub. But I´ll try to make a new request in the master area next week after the release.

**Pull request closed without merging**
