### PR TITLE
WIP FE-C calibration and configuration

### PR DESCRIPTION
**Pull request by vlcvboyer**
this add FE-C spindown time calibration and cyclist configuration messages (weight...)
- configuration is automatically done using cyclist profile in GC
- calibration is ready but not activated at present as GUI is needed ("&& false" placed in the code and pointed out with FIXME comment)

### CODE REVIEW

**Comment by vlcvboyer** [comment]
There is an issue when not compiling on win32...
I'll investigate.

**Comment by vlcvboyer** [comment]
Please wait before merging: I'll put my code on top on dresco code

**Comment by liversedge** [comment]
No problem -- let me know when you're both happy :)

**Comment by liversedge** [comment]
I would really like to get this into V3.3 if we can.

**Comment by vlcvboyer** [comment]
Yes we will do our best to have it in V3.3!

**Comment by vlcvboyer** [comment]
FYI only this is also related to #1633

**Comment by vlcvboyer** [comment]
Just to keep you informed:
it goes forward but still some issues to fix properly (concern when multiple devices are used)

**Comment by liversedge** [comment]
Any updates?

I think Jon E is working also on calibration .. wonder if it fits in with this?

**Comment by liversedge** [comment]
Any news?

**Pull request closed without merging**
