### PR TITLE
some fixes

### PR DESCRIPTION
**Pull request by andreasbuhr**
some assorted fixes

### CODE REVIEW

**Comment by liversedge** [comment]
most of these updates break code, I am not sure your approach is correct- we need to make sure the code changes are like-for-like rather than just compiling?
Also, the commit message is meaningless?

**Comment by liversedge** [comment]
although that first fix seems to be an existing bug?
is this PR a general one, not related to qt6 refactor?

**Comment by andreasbuhr** [comment]
Hi,
I created a sequence of pull requests and tried to keep only one topic in each pull request. However, unfortunately, I ran out of time and have to stop working on GoldenCheetah. I still had these changes in my working tree which I did not sort into one-topic pull requests. I did not want to discard them, so I pushed them here.

So this pull request is not intended to be merged.
Please read it as: Be aware that there are some places in the code which need more attention when porting to Qt6.

Close it if and when you like.

**Comment by liversedge** [comment]
Oh that is a shame, these PR are going to help enormously when we migrate to Qt6 and your efforts are appreciated even if we didn't say so !

If you do get a chance to return to these you will be welcomed, but for now, thank you !

**Comment by andreasbuhr** [comment]
I am happy if I it helps.
I wrote a short summary in https://github.com/GoldenCheetah/GoldenCheetah/issues/3983, probably this did not come to your attention yet.

**Comment by andreasbuhr** [comment]
I dumped some more stuff here. So this pull request is really only "other stuff I had to do to compile with Qt 6.2". Do not merge.

**Comment by liversedge** [comment]
Thats a good approach, some of these are quite interesting and potentially bugs in the code.
Glad you are back on this, following along with interest.
Mark

**Comment by amtriathlon** [comment]
It looks like we should not have problems adapting the small fixes, and we could replace QSound by QSoundEffect more or less directly, but I am not sure about replacing QWebEngineDownloadItem by QWebEngineDownloadRequest

**Comment by amtriathlon** [comment]
I am closing this since these fixes has been added to master in recente commits. I also added Andreas to our contributors list in https://github.com/GoldenCheetah/GoldenCheetah/commit/1fb92d1bf5cdf68ae6783cf7a5b0eb978416e5a1, thank you very much!

**Pull request closed without merging**
