### PR TITLE
Poor man's fixes for plural forms + updated Russian translation

### PR DESCRIPTION
**Pull request by prokoudine**
Reasoning behind changes: http://doc.qt.io/qt-4.8/i18n-source-translation.html

I'm not really a programmer, and I feel that this could be done more elegantly, but it seems to work for me.

### CODE REVIEW

**Comment by amtriathlon** [comment]
I think it is an interesting improvement, but perhaps would be better to review this after v3.2 release since applying it now would invalidate existing translations, some of which are already finished.
Is this strictly necessary for the Russian translation or just an enhancement?

**Comment by prokoudine** [comment]
"Is this strictly necessary for the Russian translation or just an enhancement?" — well, without the patch part of the translation look like a half-assed job done in terms of grammar :)

**Comment by liversedge** [comment]
I've put into the 4.0 queue since its really not that important.

**Comment by prokoudine** [comment]
Should I re-update my next translation based on upstream master branch then?

**Comment by liversedge** [comment]
If you have combined a translation update with a small code fix then sadly yes.
Its better to keep things like that separate :)

Thanks !

**Pull request closed without merging**
