### PR TITLE
Support Kurt Kinetic Inride and SmartControl

### PR DESCRIPTION
**Pull request by ericchristoffersen**
Support Kurt Kinetic Inride and SmartControl trainers over bluetooth.

I have only tested the Inride 2.0 support with windows 10.

### CODE REVIEW

**Comment by ericchristoffersen** [comment]
Latest change I put a CalibrationData object into the bt40 device and implement query through bt40controller. This lets standard trainsidebar calibration to work with bt40. Taught the kurt devices to populate the CalibrationData.

Added two new calibration_state_failure types, one for spindown too fast, another for spindown too slow. This info about spindown calibration attempt needs a way to be bubbled back to user.

This seems to work pretty well for kurt inride, and should also work for smart_control but I don't have that device to test.

Anyway, I've good confidence in the behavior of the inride support, even the calibration works really well.

**Comment by ericchristoffersen** [comment]
#3641

**Comment by amtriathlon** [comment]
Is this ready to merge, Eric?

**Comment by ericchristoffersen** [comment]
> Is this ready to merge, Eric?

Yes, I think so. Good to get mileage on the changes to calibration. I know InRide V2 works great. I don't have a smart_control device to test - guy on group said it 'worked'.

**Pull request merged**
