### PR TITLE
Fix bugs and warnings

### PR DESCRIPTION
**Pull request by bdb**
Fixes a bunch of warnings that Xcode 7 produced (and some bugs found) while working on C++11 support. Note C++11 is NOT enabled in this branch. Built and tested on 10.11.2 only. I did not test Linux build or Win build.

### CODE REVIEW

**Comment by liversedge** [comment]
Will need to read through this one, so will look on saturday when have a bit more time.

Thanks for taking the time to do this, are there any changes in there that you think are worth highlighting (regression impact / refactor would be better etc) ?

**Comment by liversedge** [comment]
**You will need to remove any changes to qwt**, since we take the base qwt libs and apply a >8  axis patch -- which we have to do when a new qwt release comes out.

So we need to minimise any changes we make. There may be an argument now to stop including qwt since it supports >8 axis now (and the code was changed to use that).

**Comment by bdb** [comment]
There is an actual Qwt bug fix: https://github.com/bdb/GoldenCheetah/commit/3143c5ee4d4df080a9d3252f4ab36526ccd1cdd7

I don't know what impact it has on GC. But you can see the very same bug that I highlighted in #1774. Basically those addDates() are NOPs when they ignore the return value.

The other stuff was just warnings. It would however be best to compile warning free. Otherwise you can have bugs hiding in the noise of mostly benign warnings.

**Comment by bdb** [comment]
The actual bugs:

https://github.com/bdb/GoldenCheetah/commit/3143c5ee4d4df080a9d3252f4ab36526ccd1cdd7
https://github.com/bdb/GoldenCheetah/commit/27a56332267fea147d693b0873a2c316388f3a70
https://github.com/bdb/GoldenCheetah/commit/f457a9cbb8b5275dc6d857df50d23d9c1ee27128

I would consider this a bug, since accessing it does not truly overload its parent method and thus accessing through a base type will not call the overloaded method (well its undefined what would really happen).
https://github.com/bdb/GoldenCheetah/commit/50db4196bf54e5f52b8bc5a50ea79904d24c37a0

And this one is a compile error when C++11 is enabled:
https://github.com/bdb/GoldenCheetah/commit/d8155c1ad100ce72da858dce75c664d9ccce3d09

**Comment by liversedge** [comment]
OK, lets merge your fixes for qwt and recognise that we should no longer keep a local copy -- rather we should link to a standard qwt lib (so before v4 is released we should remove it from the GC repo and build against the latest from Uwe).

**Comment by liversedge** [comment]
Thanks for all of these, some of them are embarrassing (!)

**Pull request merged**
