### PR TITLE
Multithread import of Files

### PR DESCRIPTION
**Pull request by mtbkeith**
Multi-threads importing of files.

I'm starting this pull request for initial feedback based on the email conversation that was about a week or two back. This addresses two things; it prevents several UI update cycles from happening when multiple files are imported (basically the model is sorted/reset/refreshed for each file). Second, it pushes two stages of the import into the background; both the validation and the saving to file. I have not tested a multi-part file which I would like to solicit help in getting such a file. The other part which I would like to polish more is that each stage waits for every portion to finish before providing UI updates as I want to separate the business logic from the UI.

There are two other small changes; one is that when you create a new Athlete, that athlete is now selected by default. Second, the default action for enter in the new athlete dialog is set to Save rather than the Avatar image selection.

### CODE REVIEW

**Comment by liversedge** [comment]
Hey! Nice stuff.

Some observations:

1. You need QFuture and QtConcurrent headers in RideImportWizard.cpp for QT5
2. The table gui updates are hidden during validate/save

I get a crash on threaded access to QStrings, which is a bummer:

0x00007ffff2c9b1f4 in operator==(QString const&, QString const&) () from /home/markl/QT/Qt5.4.0/5.4/gcc_64/lib/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff2c9b1f4 in operator==(QString const&, QString const&) () from /home/markl/QT/Qt5.4.0/5.4/gcc_64/lib/libQt5Core.so.5
#1  0x000000000086c984 in RideCache::addRideSilent (this=0x6ebd730, name=..., dosignal=<optimised out>, 
    useTempActivities=<optimised out>) at RideCache.cpp:185
#2  0x0000000000579067 in Athlete::addRideSilent (this=<optimised out>, name=..., dosignal=dosignal@entry=false, 
    useTempActivities=useTempActivities@entry=true) at Athlete.cpp:247
#3  0x00000000008bf746 in RideImportWizard::processSaveFile (this=0x76c1400, aborted=<optimised out>, filename=..., 
    i=<optimised out>) at RideImportWizard.cpp:1062
#4  0x00000000008c1da4 in QtConcurrent::StoredMemberFunctionPointerCall3<ImportFutureStatus, RideImportWizard, bool volatile*, bool volatile*, QString, QString, int, int>::runFunctor (this=0x5911a50)
    at ../../../../QT/Qt5.4.0/5.4/gcc_64/include/QtConcurrent/qtconcurrentstoredfunctioncall.h:792
#5  0x00000000008c383f in QtConcurrent::RunFunctionTask<ImportFutureStatus>::run (this=0x5911a50)
    at ../../../../QT/Qt5.4.0/5.4/gcc_64/include/QtConcurrent/qtconcurrentrunbase.h:102
#6  0x00007ffff2c06fc3 in ?? () from /home/markl/QT/Qt5.4.0/5.4/gcc_64/lib/libQt5Core.so.5
#7  0x00007ffff2c0a284 in ?? () from /home/markl/QT/Qt5.4.0/5.4/gcc_64/lib/libQt5Core.so.5
#8  0x00007ffff2606182 in start_thread (arg=0x7fff4b7fe700) at pthread_create.c:312
#9  0x00007ffff1b1347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by mtbkeith** [comment]
Thanks for the feedback, I'll have a look and will test with qt5 when I
have a chance.

**Comment by liversedge** [comment]
Running on Linux, but also use OS X when on the move :)

**Comment by mtbkeith** [comment]
Hi Mark,

I have tried in the following environments and can't reproduce a crash. As
I mentioned in the pull request this is not the final UI changes so I just
want to see if this is a workable approach and if there is sufficient
interest to complete the change.

Mac 10.8 with both Qt 4.8 and Qt 5.5, GC in debug build
Ubuntu 64-bit, 14.04.3 TLS with Qt 5.5 both release and debug
just the GC binary for linux:
https://s3.amazonaws.com/chiefer-development/goldenCheetah/GoldenCheetah-release.tar.gz

Would you mind trying a clean build and/or giving me some steps? I create a
new athlete and import about 20 test files and also bulk import about 100
of my personal fit files. Maybe it was a workout file type; do you have any
that were archive format?

Thanks,
Keith Reynolds

**Comment by liversedge** [comment]
QString and thread safety is a tricky one to fix.
I'll try and take a look at this over this week, I've got a heavy week on at work this week so bear with me...

**Comment by liversedge** [comment]
Hi Keith, I still haven't looked at this, but will pick it up.
Looking at R integration at the mo

**Comment by liversedge** [comment]
Hey Keith,

I'd like to look at this again once we start doing v4 support, are you ok if I pick up your code and have a go, or would you prefer to look at it yourself ?

Cheers

Mark

**Comment by mtbkeith** [comment]
Hi Mark, I'm happy either way! I'd like to know how to exactly reproduce
the issue that you saw with the import so I could debug it myself. I had
built a VM with Ubuntu (14.x IIRC) and couldn't get the failure. I'd love
to get this into the product. Also have been thinking some about heat-maps.

Thanks for all of your hard work on this project & coordinating. Seems like
there's been a bunch of additional contributors.

Keith

**Comment by liversedge** [comment]
Hi Keith

Would love to give this a go now with v4 dev starting .. any chance you can fix the merge conflicts ?

Mark

**Comment by mtbkeith** [comment]
Hi Mark! Yes, I'll take a look at merging my changes. Just have to get up
to date with the branch and will let you know when I have something.

Thanks for keeping this in mind!
Keith

**Comment by liversedge** [comment]
I'd love to get this working, especially since we're getting a lot of WKO3 users migrating across and they typically have hundreds of files to import .....................

.... still interested in getting this working?

(The crashes are almost certainly in metric code, not your code, so could collaborate on fixing that up)

**Comment by mtbkeith** [comment]
Hi Mark, sure I could restart on this - actually did a little work on it yesterday. I think for sanity once 'started' if all other changes to the affected files to have a moratorium for a little bit; the merges that were coming in last time caused some overhead. 

I'd love some help diagnosing the crash as I couldn't get it to happen on my machine. FYI it seems like most of the time during import is spent within '::compute' for each metric. Let's brainstorm on how to streamline and possible locations for the crash? 

grab-xcode-import-time

**Comment by liversedge** [comment]
SURE!

Do you have a patch / PR that doesn't have conflicts?

**Comment by mtbkeith** [comment]
That's what I was working on yesterday. Can get this done by early in the
week.

Thanks,
Keith

**Comment by liversedge** [comment]
Cool, will try and get some time next weekend to play with it -- it could be the userdata/usermetrics were the cause of the problem. There were some nasty threading issues in there that are now fixed.

**Comment by liversedge** [comment]
Still interested in pursuing this?

**Comment by mtbkeith** [comment]
Hi @liversedge  yes, I'm interested in pursuing still. 
Can you have a look at this and merge it? https://github.com/GoldenCheetah/GoldenCheetah/pull/2667

You can have a look at the latest work here, we can collaborate on this branch.
https://github.com/mtbkeith/GoldenCheetah/tree/GC-KR-005_ThreadImport5

**Comment by liversedge** [comment]
Ok... merged it, not sure why it was important !! :)

**Comment by mtbkeith** [comment]
Thanks, it helps to identify what portions of the table/etc are being used
during import - and to clarify for the threading part.

**Comment by liversedge** [comment]
I tried to build your branch and it seems a bit broken
e.g. on Linux its building for MacOS !?!?

**Comment by liversedge** [comment]
Oh .. wrong branch. Master seems a bit borked !

**Comment by liversedge** [comment]
Hi Keith,

Have this patch ever worked?

It crashes on addRide called from QtConcurrent updating a global variable ? (the ride cache)

**Comment by mtbkeith** [comment]
Hi Mark,

Sorry for the late reply, had a nice weekend away from the machine. Just
want to make sure you are on the right branch.  My last work was on;
GC-KR-005_ThreadImport5. I've just refreshed that branch merging in the
latest code and following with a quick test. I don't believe there are
problems with the RideCache as I'm synchronizing as follows;
```
    QMutexLocker locker(&addRideMutex);
```

There are some screen redraw issues that I captured here in a video:
https://vimeo.com/257654083 Really its just that there are only so many
threads allocated on my machine and then the parts are drawn as they become
active. I suppose the table could be filled in with a "pending" and then
update with their status.

Thanks,
Keith

**Comment by mtbkeith** [comment]
There might be one other issue outside of the RideCache where I added
future watchers, there's a chance that

futureSaveFinished would not be called or the object could go out of scope
because it is on the stack.


Keith

**Comment by liversedge** [comment]
Ah ok. The mutex wasn't there before. Will look at it, as its very promising indeed.
Will play with it this weekend -- getting the screen to refresh should be easy enough.

**Comment by liversedge** [comment]
Hi @mtbkeith can you push your updates to the threaded branch? last commit was last november.

**Comment by liversedge** [comment]
Oh FFS, Just ignore me. first entry in git log is old, but all other commits are there. Will play with this. Leave it with me.

**Comment by liversedge** [comment]
Its freaking awesome on my Linux box (admittedly its got 6 cores and 12 threads).
Will clean up the refresh and other nits and try and pull into the code this weekend.

**Comment by mtbkeith** [comment]
Sweet! As I last mentioned I think the future watcher can be a problem for
short running jobs. Can we get a couple more eyes on it, or would a Dev
build be sufficient?

The git history date is off since I rebased my changes and did a force push.

Keith

**Comment by liversedge** [comment]
I'm fixing and working with it now. Its right that I am involved since the interaction with the ride cache, estimates etc needs to be adjusted to reflect async updates.

I've been testing with importing a zip file from trainingpeaks and its getting there. Its tickled quite a lot of other "bugs" in the code that I'm working through.

Will post update a bit later.

**Comment by mtbkeith** [comment]
Very good, happy to collaborate on this or another branch if needed.

**Comment by liversedge** [comment]
It does look like there is no performance gain once the rides are parsed. This is because the metric compute uses threads anyway.

Will keep playing, but the added complexity might not be worth the effort :(

**Comment by liversedge** [comment]
I have a number of updates to get this patch working, so would be good to share back. Will attach a patch.

**Comment by liversedge** [comment]
diff --git a/src/Core/Athlete.cpp b/src/Core/Athlete.cpp
index c8383c4a..7d88fbcc 100644
--- a/src/Core/Athlete.cpp
+++ b/src/Core/Athlete.cpp
@@ -62,6 +62,9 @@ Athlete::Athlete(Context *context, const QDir &homeDir)
     context->athlete = this;
     cyclist = this->home->root().dirName();
 
+    // not importing
+    importing = false;
+
     // get id and set id all at one
     id = QUuid(appsettings->cvalue(cyclist, GC_ATHLETE_ID, QUuid::createUuid().toString()).toString());
     appsettings->setCValue(cyclist, GC_ATHLETE_ID, id.toString());
@@ -268,10 +271,10 @@ void Athlete::selectRideFile(QString fileName)
     context->notifyRideSelected(context->ride);
 }
 
-void
+RideItem *
 Athlete::addRide(QString name, bool dosignal, bool select, bool useTempActivities, bool planned)
 {
-    rideCache->addRide(name, dosignal, select, useTempActivities, planned);
+    return rideCache->addRide(name, dosignal, select, useTempActivities, planned);
 }
 
 void
@@ -466,7 +469,7 @@ Athlete::getPDEstimates()
     QList<PDEstimate> returning;
 
     // access is via mutex because its updated in another thread
-    if (lock.tryLock(100)) {
+    if (rideCache->refreshingEstimates == false && lock.tryLock(100)) {
         returning = PDEstimates_;
         lock.unlock();
     }
diff --git a/src/Core/Athlete.h b/src/Core/Athlete.h
index 0ad40d0d..e46b8b13 100644
--- a/src/Core/Athlete.h
+++ b/src/Core/Athlete.h
@@ -126,6 +126,7 @@ class Athlete : public QObject
 #endif
 
         // Athlete's autoimport handling
+        bool importing;
         RideImportWizard *autoImport;
         RideAutoImportConfig *autoImportConfig;
 
@@ -144,7 +145,7 @@ class Athlete : public QObject
 
         // ride collection
         void selectRideFile(QString);
-        void addRide(QString name, bool signal, bool select=true, bool useTempActivities=false, bool planned=false);
+        RideItem *addRide(QString name, bool signal, bool select=true, bool useTempActivities=false, bool planned=false);
         void removeCurrentRide();
 
         // zones etc
diff --git a/src/Core/RideCache.cpp b/src/Core/RideCache.cpp
index a7914ecb..c740a5e7 100644
--- a/src/Core/RideCache.cpp
+++ b/src/Core/RideCache.cpp
@@ -211,7 +211,7 @@ RideCache::itemChanged()
 }
 
 // add a new ride
-void
+RideItem *
 RideCache::addRide(QString name, bool dosignal, bool select, bool useTempActivities, bool planned)
 {
     RideItem *prior = context->ride;
@@ -221,7 +221,7 @@ RideCache::addRide(QString name, bool dosignal, bool select, bool useTempActivit
     if (!RideFile::parseRideFileName(name, &dt))
     {
         qCritical() << "Failed to parse ride filename: " << name;
-        return;
+        return NULL;
     }
     
     // new ride item
@@ -237,11 +237,11 @@ RideCache::addRide(QString name, bool dosignal, bool select, bool useTempActivit
     connect(last, SIGNAL(rideMetadataChanged()), this, SLOT(itemChanged()));
 
     // prevent multiple threads from adding to the cache
+    bool added = false;
     {
     QMutexLocker locker(&addRideMutex);
     
         // now add to the list, or replace if already there
-        bool added = false;
         for (int index=0; index < rides_.count(); index++) {
             if (rides_[index]->fileName == last->fileName) {
                 rides_[index] = last;
@@ -252,39 +252,45 @@ RideCache::addRide(QString name, bool dosignal, bool select, bool useTempActivit
 
         // add and sort, model needs to know !
         if (!added) {
-            model_->beginReset();
-            rides_ << last;
-            qSort(rides_.begin(), rides_.end(), rideCacheLessThan);
-            model_->endReset();
-        }
-    
-        // TODO: This is the part that takes all the time - do it outside the mutex so multiple threads can cooperate
-        // refresh metrics for *this ride only*
-        last->refresh();
+            // where is it going?
+            for(int i=0; i<rides_.count();i++) {
+                if (last->dateTime < rides_[i]->dateTime) {
+                    rides_.insert(i, last);
+                    model_->insertRow(i, QModelIndex());
+                    added = true;
+                    break;
+                }
+            }
 
-        if (dosignal)
-        {
-            context->notifyRideAdded(last); // here so emitted BEFORE rideSelected is emitted!
+            if (!added) {
+                rides_ << last;
+                model_->insertRow(rides_.count(), QModelIndex());
+                added = true;
+            }
         }
-
+    
     } //- close the mutex
 
-    // free up memory from last one, which is no biggie when importing
-    // a single ride, but means we don't exhaust memory when we import
-    // hundreds/thousands of rides in a batch import.
-    if (prior)
-    {
-        prior->close();
+    // TODO: This is the part that takes all the time - do it outside the mutex so multiple threads can cooperate
+    // refresh metrics for *this ride only*
+    last->refresh();
+
+    if (dosignal) {
+        context->notifyRideAdded(last); // here so emitted BEFORE rideSelected is emitted!
     }
-// TODO: move this selection to after the save finish?
+
+
     // notify everyone to select it
     if (select) {
         context->ride = last;
         context->notifyRideSelected(last);
-    } else {
-        // notify everyone to select the one we were already on
-        context->notifyRideSelected(prior);
+
+        // free up memory from last one, which is no biggie when importing
+        // a single ride, but means we don't exhaust memory when we import
+        // hundreds/thousands of rides in a batch import.
+        if (prior) prior->close();
     }
+    return last;
 }
 
 void
@@ -704,7 +710,7 @@ void
 RideCache::refreshCPModelMetrics()
 {
     // we're refreshing, so away
-    if (refreshingEstimates == true) return;
+    if (context->athlete->importing == true || refreshingEstimates == true) return;
 
     // need to lock
     refreshingEstimates = true;
diff --git a/src/Core/RideCache.h b/src/Core/RideCache.h
index ae309ff4..f88bfc50 100644
--- a/src/Core/RideCache.h
+++ b/src/Core/RideCache.h
@@ -87,7 +87,7 @@ class RideCache : public QObject
 	    QVector<RideItem*>&rides() { return rides_; } 
 
         // add/remove a ride to the list
-        void addRide(QString name, bool dosignal, bool select, bool useTempActivities, bool planned);
+        RideItem *addRide(QString name, bool dosignal, bool select, bool useTempActivities, bool planned);
         void removeCurrentRide();
 
         // export metrics in CSV format
@@ -131,6 +131,7 @@ class RideCache : public QObject
     protected:
 
         friend class ::RideCacheBackgroundRefresh;
+        friend class ::Athlete;
 
         // mutex to limit adding in cache
         QMutex addRideMutex;
diff --git a/src/Core/RideCacheModel.cpp b/src/Core/RideCacheModel.cpp
index e7c68418..7b956e49 100644
--- a/src/Core/RideCacheModel.cpp
+++ b/src/Core/RideCacheModel.cpp
@@ -179,6 +179,13 @@ RideCacheModel::headerData(int section, Qt::Orientation orientation, int role) c
     return QVariant();
 }
 
+bool
+RideCacheModel::insertRows(int row, int count, const QModelIndex &parent)
+{
+    beginInsertRows(QModelIndex(), row, row+count-1);
+    endInsertRows();
+}
+
 // when updating metadata config
 void 
 RideCacheModel::configChanged(qint32)
diff --git a/src/Core/RideCacheModel.h b/src/Core/RideCacheModel.h
index 8957fcc5..289b2d31 100644
--- a/src/Core/RideCacheModel.h
+++ b/src/Core/RideCacheModel.h
@@ -47,6 +47,7 @@ class RideCacheModel : public QAbstractTableModel
         QVariant headerData(int section, Qt::Orientation orientation, int role = Qt::DisplayRole ) const;
         bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role =Qt::EditRole);
         QVariant data(const QModelIndex &index, int role = Qt::DisplayRole) const;
+        bool insertRows(int row, int count, const QModelIndex &parent = QModelIndex());
 
     public slots:
 
diff --git a/src/Gui/RideImportWizard.cpp b/src/Gui/RideImportWizard.cpp
index b4e23e51..f6254659 100644
--- a/src/Gui/RideImportWizard.cpp
+++ b/src/Gui/RideImportWizard.cpp
@@ -247,7 +247,7 @@ RideImportWizard::RideImportWizard(RideAutoImportConfig *dirs, Context *context,
 }
 
 void
-RideImportWizard::init(QList<QString> original, Context * /*mainWindow*/)
+RideImportWizard::init(QList<QString> original, Context *context)
 {
     // expand files if they are archives - this may involve unzipping or extracting
     //                                     files into a subdirectory, so we also clean-up
@@ -258,6 +258,9 @@ RideImportWizard::init(QList<QString> original, Context * /*mainWindow*/)
     HelpWhatsThis *help = new HelpWhatsThis(this);
     this->setWhatsThis(help->getWhatsThisText(HelpWhatsThis::MenuBar_Activity_Import));
 
+    // set importing flag
+    context->athlete->importing = true;
+
     // initialise dialog box
     tableWidget = new QTableWidget(files.count(), 6, this);
 
@@ -430,7 +433,7 @@ RideImportWizard::init(QList<QString> original, Context * /*mainWindow*/)
     connect(this, SIGNAL(sig_announceProgress(int, bool, QString)), this, SLOT(announceProgress(int, bool, QString)));
     connect(this, SIGNAL(sig_setRideDuration(int, int, double)), this, SLOT(setRideDuration(int, int, double)));
     connect(this, SIGNAL(sig_setRideDateTime(int, QDateTime)), this, SLOT(setRideDateTime(int, QDateTime)));
-
+    rowshown=0;
 }
 
 QList<QString>
@@ -483,6 +486,7 @@ void RideImportWizard::announceProgress(int index, bool valid, const QString mes
 //        return;
     tableWidget->item(index,WizardTable::STATUS_COLUMN)->setText(message);
     tableWidget->viewport()->update();
+    showrow(index);
 }
 
 void RideImportWizard::setRideDateTime(int index, QDateTime startTime)
@@ -505,6 +509,7 @@ void RideImportWizard::setRideDateTime(int index, QDateTime startTime)
     
     tableWidget->item(index,WizardTable::DATE_COLUMN)->setTextAlignment(Qt::AlignHCenter | Qt::AlignVCenter); // put in the middle
     tableWidget->item(index,WizardTable::TIME_COLUMN)->setTextAlignment(Qt::AlignHCenter | Qt::AlignVCenter); // put in the middle
+    showrow(index);
 }
 
 void RideImportWizard::setRideDuration(int index, int secs, double km)
@@ -522,6 +527,21 @@ void RideImportWizard::setRideDuration(int index, int secs, double km)
     : QString ("%1 mi").arg(km * MILES_PER_KM, 0, 'f', 1);
     tableWidget->item(index,WizardTable::DISTANCE_COLUMN)->setText(dist);
     tableWidget->item(index,WizardTable::DISTANCE_COLUMN)->setTextAlignment(Qt::AlignRight | Qt::AlignVCenter);
+    showrow(index);
+}
+
+void
+RideImportWizard::showrow(int row)
+{
+    // always go to row 0 as jumps back in each phase
+    if (row <10 || row > rowshown) {
+        rowshown = row;
+        tableWidget->scrollTo(tableWidget->model()->index(row,0));
+    }
+
+    // even if not scrolling something changed
+    repaint();
+    QApplication::processEvents();
 }
 
 void RideImportWizard::longRunningFunction(Context *context, const QObject *m_receiver, const QString &filename, const int index) //, ConvertFileTask &foo)
@@ -1506,9 +1526,8 @@ RideImportWizard::save_async(Context *context, const QObject *m_receiver, const
     if (tableWidget->item(index,WizardTable::STATUS_COLUMN)->text().startsWith(tr("Error")))
         return; // skip errors
     
-    tableWidget->item(index,WizardTable::STATUS_COLUMN)->setText(tr("Saving..."));
-//    tableWidget->setCurrentCell(index,WizardTable::STATUS_COLUMN);
-//    QApplication::processEvents();
+    emit sig_announceProgress(index, true, tr("Saving..."));
+
     if (aborted)
     {
         //done(0);
@@ -1536,7 +1555,8 @@ RideImportWizard::save_async(Context *context, const QObject *m_receiver, const
     // check if a ride at this point of time already exists in /activities - if yes, skip import
     if (QFileInfo(finalActivitiesFulltarget).exists())
     {
-        tableWidget->item(index,WizardTable::STATUS_COLUMN)->setText(tr("Error - Activity file exists"));
+        emit sig_announceProgress(index, true, tr("Error - Activity file exists"));
+        //XXXshowrow(index);
         return;
     }
     
@@ -1546,7 +1566,8 @@ RideImportWizard::save_async(Context *context, const QObject *m_receiver, const
     // while the computer has been set to a different time zone
     if (context->athlete->rideCache->getRide(ridedatetime.toUTC()))
     {
-        tableWidget->item(index,WizardTable::STATUS_COLUMN)->setText(tr("Error - Activity file with same start date/time exists"));
+        emit sig_announceProgress(index, true, tr("Error - Activity file with same start date/time exists"));
+        //XXXshowrow(index);
         return;
     };
     
@@ -1565,7 +1586,7 @@ RideImportWizard::save_async(Context *context, const QObject *m_receiver, const
         // copy the source file to /imports with adjusted name
         QFile source(filenames[index]);
         if (!source.copy(importsFulltarget)) {
-            tableWidget->item(index,WizardTable::STATUS_COLUMN)->setText(tr("Error - copy of %1 to import directory failed").arg(importsTarget));
+            emit sig_announceProgress(index, true, tr("Error - copy of %1 to import directory failed").arg(importsTarget));
         }
     } else {
         // file is re-imported from /imports - keep the name for .JSON Source File Tag
@@ -1578,7 +1599,8 @@ RideImportWizard::save_async(Context *context, const QObject *m_receiver, const
     // -- second  create RideCache() entry
     // -- third   move file from /tmpactivities to /activities
     
-    tableWidget->item(index,WizardTable::STATUS_COLUMN)->setText(tr("Saving file..."));
+    emit sig_announceProgress(index, true, tr("Saving file..."));
+    //XXXshowrow(index);
     
     // serialize the file to .JSON
     QStringList errors;
@@ -1611,29 +1633,30 @@ RideImportWizard::save_async(Context *context, const QObject *m_receiver, const
             // is stored in tmpActivities during this process to understand which file has create the problem when restarting GC
             // - only after the step was successful the file is moved
             // to the "clean" activities folder
-            
-            // TODO: semaphore?
-            
-            context->athlete->addRide(QFileInfo(tmpActivitiesFulltarget).fileName(),
+            RideItem *added = context->athlete->addRide(QFileInfo(tmpActivitiesFulltarget).fileName(),
                                       // TODO: only signal last one?
                                       false, // don't signal if mass importing
-                                      true,
+                                      false,
                                       true);                                       // file is available only in /tmpActivities, so use this one please
             // rideCache is successfully updated, let's move the file to the real /activities
             if (moveFile(tmpActivitiesFulltarget, finalActivitiesFulltarget)) {
                 // TODO: needs to be put in background
-                tableWidget->item(index,WizardTable::STATUS_COLUMN)->setText(tr("File Saved"));
+                emit sig_announceProgress(index, true, tr("File Saved"));
+                //XXXshowrow(index);
                 // and correct the path locally stored in Ride Item
-                context->ride->setFileName(homeActivities.canonicalPath(), activitiesTarget);
+                if (added) added->setFileName(homeActivities.canonicalPath(), activitiesTarget);
             }  else {
-                tableWidget->item(index,WizardTable::STATUS_COLUMN)->setText(tr("Error - Moving %1 to activities folder").arg(activitiesTarget));
+                emit sig_announceProgress(index, true, tr("Error - Moving %1 to activities folder").arg(activitiesTarget));
+                //XXXshowrow(index);
             }
             
         }  else {
-            tableWidget->item(index,WizardTable::STATUS_COLUMN)->setText(tr("Error - .JSON creation failed"));
+            emit sig_announceProgress(index, true, tr("Error - .JSON creation failed"));
+            //XXXshowrow(index);
         }
     } else {
-        tableWidget->item(index,WizardTable::STATUS_COLUMN)->setText(tr("Error - Import of activitiy file failed"));
+        emit sig_announceProgress(index, true, tr("Error - Import of activitiy file failed"));
+        //XXXshowrow(index);
     }
     
     // now metrics have been calculated
@@ -1948,6 +1971,7 @@ RideImportWizard::done(int rc)
 RideImportWizard::~RideImportWizard()
 {
     foreach(QString name, deleteMe) QFile(name).remove();
+    context->athlete->importing = false;
 }
 
 
diff --git a/src/Gui/RideImportWizard.h b/src/Gui/RideImportWizard.h
index 6e2f0ca0..d0b0cc87 100644
--- a/src/Gui/RideImportWizard.h
+++ b/src/Gui/RideImportWizard.h
@@ -85,6 +85,8 @@ private slots:
     void futurePreProcessFinished();
     void futureSaveFinished();
 
+    void showrow(int row);
+
 private:
     void init(QList<QString> files, Context *context);
     bool moveFile(const QString &source, const QString &target);
@@ -94,6 +96,7 @@ private:
 
     QList <QString> filenames; // list of filenames passed
     int numberOfFiles; // number of files to be processed
+    int rowshown; // last row shown and scrolled to
     QList <bool> blanks; // record of which have a RideFileReader returned date & time
     QDir homeImports; // target directory for source files
     QDir homeActivities; // target directory for .JSON
diff --git a/src/Gui/RideNavigator.cpp b/src/Gui/RideNavigator.cpp
index 188143a9..30b2bd49 100644
--- a/src/Gui/RideNavigator.cpp
+++ b/src/Gui/RideNavigator.cpp
@@ -951,7 +951,7 @@ void
 RideNavigator::setRide(RideItem*rideItem)
 {
     // if we have a selection and its this one just ignore.
-    if (currentItem == rideItem && tableView->selectionModel()->selectedRows().count() != 0) return;
+    if (rideItem == NULL || (currentItem == rideItem && tableView->selectionModel()->selectedRows().count() != 0)) return;
 
     for (int i=0; i<tableView->model()->rowCount(); i++) {

**Comment by liversedge** [comment]
I will take the learnings into the main repo regards crashes it tickled:
1. don't refresh PD estimates when the import is running
2. addRide should return the RideItem * so the ImportWizard can work with it (not via context->ride)
3. rideNavigator->setRide should check for NULL

The model reset in the ride list sidebar is fugly, but will leave it alone as it works, if a bit slowly.

**Pull request closed without merging**
