### PR TITLE
Qt6: adapt checksum methods

### PR DESCRIPTION
**Pull request by andreasbuhr**
This is incompatible with Qt 5.15 and must not be merged before really going to Qt 6.

Probably it will change checksums of UserMetricSettings. If this is not acceptable, this needs more work.

### CODE REVIEW

**Comment by liversedge** [comment]
The code should be adapted to check the QT version, e.g.
```
#if QT_VERSION >= 0x060000
    // do the Qt6 code
#else 
   // do the current code
#endif 
```

**Comment by andreasbuhr** [comment]
Ah, do you plan to be compatible with both Qt5 and Qt6 for a while?

**Comment by liversedge** [comment]
Absolutely. It helps the transition not just for the team, but for building and distribution.
It is unlikely that Qt6 will be stable for a few months, so we are not likely to just jump to it.

**Comment by andreasbuhr** [comment]
I changed this back to use the qChecksum(QByteArray, qsizetype size) methods. While they are deprecated, they still exist in Qt 6.2.

**Comment by amtriathlon** [comment]
Thank you!

**Pull request merged**
