### PR TITLE
Added Swedish translation

### LINKED ISSUE #2201: Swedish translation imminent
Hi,
just want to mention that in a few days I should be finished with the first run-through of the swedish translation. Still struggling to create an environment to do my own builds but I guess that will sort itself out with time. Meanwhile, where should I put/send the file? Seen some were published on the google groups forum. Big thanks to the German translators - did help a lot to have input from two languages (and the c++ "translator" as well :-) Do make it easier to understand context better. If someone wants a "pipecleaner" version asap, Just let me know. /Henrik

### PR DESCRIPTION
**Pull request by amtriathlon**
Initial translation contributed by Henrik Johansson,
recognition added to contributors list.
Fixes #2201

### CODE REVIEW

**Comment by henolo** [comment]
Lacking better place to post to. Just tried to publish some small changes to repository but that didn't work. Probably lacking rights to write. Do I need to apply somewhere ?

**Comment by amtriathlon** [comment]
Hi Henrik, we are using github Pull Requests to change the main repository, there are several online tutorials about how to create one, if you don't want to mess with git just email me the updated gc_sv.ts file and I will do it for you.

**Comment by henolo** [comment]
Did look at some of the (very basic) git tutorials and learnt a thing or two...
Running  github desktop 
[gc_sv.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/622942/gc_sv.txt)
Get error messages like: "Sync failed to push local... you do not have permission..." etc. when doing a pull request.
So I put a new file here. 
These Key accelerators appear strange to me, the 3.4 on windows don't even match (the english) marked alt and ctrl keys. /Henrik

**Comment by amtriathlon** [comment]
Hi Henrik, I've tested a couple of accelerators on english and swedish and they seem to work ok, for example to open a download dialog:
- English: Alt+c+d or Ctrl+d
- Swedish: Alt+a+d or Ctrl+d

are working on my linux build

I've committed your changes, an alternative procedure could be to create an issue with the compressed gc_sv.ts file attached which we can close with the corresponding commit.

To create a pull request you need to create your own fork first to be able to push your local changed on the forked github repository and then to create the pull request from there, this is explained here: https://help.github.com/articles/fork-a-repo/ and https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Thanks for your contribution!

**Comment by henolo** [comment]
Interestingly on windows i get (as already stated):

 

Some 3.4 working ctrl codes are not even marked up in the english texts with ”&” and some use different letter and some don’t show up at all (appear blocked).

Something weird with windows build then. 

Don’t know how big issue this really is – only time I use fast keyboard commands is when I repeat the same thing over and over.

And have not run into this need with GC (yet?).

 

Regarding my git learning curve…

Yes did not understand that I needed to fork first and that a branch is not a fork, and that a fork really is a “twig” (according to some) – didn’t even know that there were two different major approaches to use git.

Of which one was similar to my previous view on how it might work.

 

It is fun to (have) learn(t) things!

 

Will try this next time.

 

Från: Alejandro Martinez [mailto:notifications@github.com] 
Skickat: den 30 november 2016 22:31
Till: GoldenCheetah/GoldenCheetah
Kopia: Henrik; Comment
Ämne: Re: [GoldenCheetah/GoldenCheetah] Added Swedish translation (#2212)

 

Hi Henrik, I've tested a couple of accelerators on english and swedish and they seem to work ok, for example to open a download dialog:

*	English: Alt+c+d or Ctrl+d
*	Swedish: Alt+a+d or Ctrl+d

are working on my linux build

I've committed your changes, an alternative procedure could be to create an issue with the compressed gc_sv.ts file attached which we can close with the corresponding commit.

To create a pull request you need to create your own fork first to be able to push your local changed on the forked github repository and then to create the pull request from there, this is explained here: https://help.github.com/articles/fork-a-repo/ and https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Thanks for your contribution!

**Comment by amtriathlon** [comment]
Hi Henrik, we are looking for to release v3.5, do you like to update your translation?
Cheers, Ale.

**Comment by henolo** [comment]
Hi Ale,

great news! 

 

Sure are a few things to correct, complete, improve but if 3.5 release is imminent I think it is ok. 

 

Is there some kind of plan/schedule/deadline to adhere to?

 

Thanks

Henrik

 

Från: Alejandro Martinez [mailto:notifications@github.com] 
Skickat: den 18 augusti 2019 02:06
Till: GoldenCheetah/GoldenCheetah <GoldenCheetah@noreply.github.com>
Kopia: Henrik <henrik@hallfose.com>; Comment <comment@noreply.github.com>
Ämne: Re: [GoldenCheetah/GoldenCheetah] Added Swedish translation (#2212)

 

Hi Henrik, we are looking for to release v3.5, do you like to update your translation?
Cheers, Ale.

**Comment by amtriathlon** [comment]
The code is feature complete and all texts to translate are finished, I think we will need a couple of RC build before release, but I haven't got a schedule.

**Pull request merged**
